[id="con_further_studies_on_a_low_level_model_montgomery_{con-further-studies-on-a-low-level-model-montgomery}"]
include::../attributes.adoc[]

== Model

In order that the model reported by Davisfootnote:1[W. E. Davis, “A Model to Compute Lower Level Montgomery Stream Functions - Part II,” Pacific Northwest Laboratories Annual Report for 1974 to the USAEC Division of Biology and Environmental Research, Part 3, Atmospheric Sciences, BNWL-1950 PT 3, Battelle, Pacific Northwest, Laboratories, Richland, WA, February 1975.] may be used at various locations, a number of changes were made. One of the changes was that the latitude and longitude of the radiosonde stations were used as input. The maximum and minimum latitude along with the maximum and minimum longitude were used as four corners of a rectangular grid. The assumption was then made that the data at the radiosonde sites had been bilinearly interpolated from the four grid corners. This yielded a set of four equations easily solved for the four grid corners. The data was then linearly interpolated in time to produce a sounding for the hourly reporting stations. The model was run to produce Montgomery stream functions (ψ) as a function of potential temperature at each of the hourly sites. This data can then be used to compute trajectories.

Since the trajectories to be calculated will be near fronts, a decision was made to include in the model a program to compute the gradient winds. These winds can then be used for transporting the air parcels. One concern, though, is with the error generated in the gradient winds through erroneous strain functions. Since the model has been changed, it was decided that another error study was necessary.

A series of comparisons were made with the pressures of potential temperature surfaces as derived from the generalized model to the values derived from the old mode. The result was that the new pressures were usually within a few millibars of the pressures calculated by the old model. While making these comparisons, two problems were found in the model. The first problem was that superadiabatic lapse rates were being artificially produced in the soundings. This caused cases where the potential temperature of the first level was less than the surface potential temperature. To correct this a level was found where the potential temperature was greater than the surface temperature. A linear change was assumed in the potential temperature between the surface and the new level.

The second problem in the model was the maintaining of relative spacing between potential temperature surfaces. (This was used previously when the surface potential temperature minus the potential temperature of the first level was greater than 1° A.) The model now assumes a linear change in potential temperature between the surface and the first level above the surface. With these changes the model was rerun for August and November, 1972. The model’s stream functions were compared with those computed from radiosonde data.

== Results

As can be seen in *Tables 1 - 5*, the data produced by the revised model are generally more accurate than the old model. The main beneficial effect was seen in the 0700 PST data in August for SEA and in the 1300 PST data in November for PDX and in August for SEA. More work will be required to take into account the surface heating effects for 1300 PST data. Since changing the model, we are now able to lift the restriction of the computation of stream functions within 100 mb of the surface pressure, while still using the Δθ* (see *Tables 1 - 5*) restriction of 5° A for the 0700 PST data and 2-3° A for the 1300 PST data.

== Conclusions

The model reported by Davis has been generalized to compute hourly values of stream functions anywhere there are four radiosonde stations with at least twelve hourly reports. Also, the output of the model has been gridded and a gradient wind routine developed for use in frontal storms. The model also has been altered to yield generally more accurate values for 0700 PST with a slight decrease in accuracy at 1300 PST. The main result is the lifting of the previous year’s restriction on computation of the stream functions within 100 mb of the surface pressure. With the Δθ restrictions listed above, we are able to produce stream functions with errors within ± 0.05 x 10^7^ cm^2^ sec^2^.

NOTE: *Δθ = Potential temperature of a level-surface potential temperature.