== Introduction

The first significant injection of transuranium elements into the atmosphere was the result of the nuclear weapons test in Alamogordo, New Mexico on July 6, 1945. Between then and 1952 further nuclear detonations resulted in additional injections to the atmosphere, however most of this debris was confined to the troposphere

In 1952 the first thermonuclear device was tested resulting in a much higher energy yield of the fusion devices is accompanied by a much higher generation of neutrons. This in turn greatly increases the production of the transuranium elements and other nuclear debris which has been interjected into the atmosphere was produced during the 1961-1962 U.S. and USSR nuclear weapons testing programs. Most of the studies of transuranium elements from nuclear weapons testing have been concerned with the measurement of Pu isotopes. However, the complete decay of the short-lived ^241^Pu (15 yrs) will result in a greater residue of ^241^Am activity than of ^239^Pu.

The operation of nuclear reactors also results in the production of transuranium elements and there exists the potential of release of some of these to the atmosphere. The modern nuclear power plants which are designed for the generation of electrical energy employ very long fuel exposure periods. This results in successive neutron capture of the transuranium elements and is productive of very long fuel exposure periods.

This results in successive neutron capture of the transuranium elements will be produced as a result of energy generation by the year 2000. Whereas Pu and Am isotopes are the main transuranium activities from nuclear weapons testing, ^241^Am and the curium isotopes will be the principal activities resulting from the nuclear power generation.

A major injection of ^238^Pu into the atmosphere occurred in April of 1964 when a satellite failed to achieve a stable orbit and disintegrated in re-entry into the atmosphere. The 17 KCi which was added to the atmosphere was relatively small compared with 350/kilocuries of ^239-240^Pu which has been added by nuclear weapons testing. However, its point source injection has been useful in developing models describing global atmospheric mixing. Accidental releases of transuranium elements to the atmosphere have occurred both from nuclear plant operation and from the transport of nuclear weapons. The total amounts released to the atmosphere by these processes have been relatively minor, however such accidents can have rather serious local effects.

== Transuranium Elements from Nuclear Explosions

Prior to the detonation of the first thermonuclear device in 1952, atmospheric injections were confined mainly to the troposphere and most of the transuranic isotopes were of mass than 243. In debris from the Ivy Mike shot on November 1 of 1952, elements of mass through 255 were observed. The much higher yield of the Ivy Mike device than that of earlier devices permitted the multiple neutron capture by uranium, which allowed production of the very heavy elements. In the detonation process, multiple neutron capture by 328U results in the production of extremely neutron-rich products, the beta decay of which produces nuclides along the line of greatest stability. *Table 1* shows the relative abundance of the transuranium isotopes which were formed in the Ivy Mike test. The isobars of significant half-life are shown together with their decay properties and half-lives. Their total activities are normalized to 239Pu to permit comparison of their relative production rates. It is evident that 241Pu (a beta decay isotope) and in later years 241Am are the most abundant activities. The production of large amounts of transuranium isotopes in the Ivy Mike test stimulated an interest in the use of nuclear explosions for the production of transuranium isotopes. In subsequent tests conducted by the Los Alamos Scientific Laboratory and the Livermore Laboratory, neutron fluxes as great as twentyfold those in the Ivy Mike device were achieved. These very high fluxes produced the heavy isotope fermium concentrations several orders of magnitude higher relative to 240Pu than in the Ivy Mike test. From these tests it was calculated that the production beyond mass 257 was not likely to occur unless very substantially higher neutron fluxes were achieved. It is believed an island of stability near mass 289 and atomic No. 114 exists, but to produce such an isotope would require a substantially higher flux than has been realized in nuclear detonations.

== Transuranium Nuclides from Reactor Operation

With the use of very high exposure fuels for energy generation, the production of transuranium elements through the end of the century will be very substantial. It has been estimated that approximately one-quarter million tons of radioactive wastes will be generated which will include approximately 109 curies of transuranium elements. In generation of energy by nuclear reactors, both ^235^U and the ^239^Pu will be burned to the highest degree possible. In the exposure of these fuels, very substantial amounts of Am and Cm isotopes will be formed. For example, as known in *Table 2*, the activity ratios of ^241^Am and/of 242-244 will be hundreds to thousands of times greater than that of ^239^Pu. The potential environmental impact of these transplutonium elements should therefore be of major concern relative to ^239-240^Pu. Because of their methods of production, the relative abundances of the transuranium elements are considerably different from nuclear detonations than from reactor operations. In nuclear detonations, neutron capture occurs in extremely rapid succession, producing very high mass uranium isotopes which could break the chain of successive neutron capture. In the reactor production of radionuclides, the neutrons are captured only one at a time and the resulting product may decay prior to additional neutron capture. In *Table IV* the amounts of the various transuranium elements resulting dfrom the Ivy Mike nuclear test are compared with those which result from nuclear power generation. It is immediately evident that the transuranium elements resulting from nuclear energy generation are much higher relative to 239PU in the region just above plutonium, than for those from nuclear weapons testing.

Reported releases of transuranium elements from nuclear plant operations indicate that in general these have been very small. Loss of material around the Rocky Flats plant has resulted in some environmental contamination. Accidents involving nuclear-weapons-carrying aircraft have resulted in the spread of plutonium over limited areas, however these appear to have resulted in rather minor injections of Pu into the atmosphere.

== Transuranium Nuclides in the Atmosphere

Since the testing of the first termonuclear device in 1952, substantial amounts of fission products, as well as transuranium elements, have entered the stratosphere. These injections result in the long-term, relatively slow deposition of radioactivity over the entire surface of the earth. Empirical box models which describe the movement of radioactivity from the upper to the lower stratosphere, between hemispheres, from the stratosphere to the to the troposphere, and the deposition rate on the earth’s surface have been developed and appear to be reasonably satisfactory. As a first approximation, the transuranium elements appear to behave in their atmospheric transport in essentially the same manner as other fission products. It has been shown, for example, that the ratio of ^90^Sr to ^239-240^Pu to ^137^Cs ratio for the past decade. This ratio appears to be constant within the accuracy of the measurements and thus tends to confirm the constancy of the transuranium behavior relative to that of the fission products. *Figure 2* shows the concentrations of ^238^Pu and ^239^Pu from 1962 to the present. 

These measurements, which were made near our laboratory at Richland, Washington, show that seasonal variations in the ^238-239^Pu were similar to those of other nuclear-weapons-produced radionuclides of stratospheric origin; maximum concentrations occurring the late spring and minimum occurring in the winter. The rate of decrease in the ^239-240^Pu concentration from 1963 through 1967 corresponded to a stratospheric half-residence time of 10 to 11 months, which is the same as the half-residence times calculated from measurement of other radionuclides of stratospheric origin. The ^239^Pu concentrations remained fairly constant from 1967 to 1972, primarily because of yearly injections of plutonium by thermonuclear tests conducted by the Chinese at Lop Nor (35° N); the contribution from the French tests in the South Pacific (23° S) may also have been significant. Relatively large amounts of the short ^237^U and ^239^Np were also observed following the individual tests.

From 1962 through 1965 the ^238^Pu and the 239Pu in surface air at Richland came primarily from the 1961-62 U.S.and USSR series. The ^238^Pu/^239^Pu ratio averaged 0.015 in 1964. The ratio increased slightly in 1965, and by the spring of 1966 it had increased to 0.042, indicating that ^238^Pu from the SNAP-9A burnup was present. The amount of SNAP-9A ^238^Pu present was calculated from the ^238^Pu concentrations and the ^238^Pu/^239^Pu ratios, assuming the ratio in debris from nuclear weapons tests was 0.015. These calculations indicate that the ^238^Pu in Richland air from 1967 to 1971 came primarily from SNAP-9A. From 1967 through 1969 the concentrations of SNAP-9A plutonium at Richland remained fairly constant, indicating that the ^238^Pu was being transferred across the equator into the northern hemisphere at a rate comparable to the rate at which ^238^Pu was being deposited on the earth’s surface. The ^238^Pu concentrations showed seasonal variation typical of radionuclides of stratospheric origin, so the transfer was probably taking place primarily in the stratosphere. Concentrations of SNAP-9A plutonium at Richland have decreased rapidly since that time. These results indicate that the stratospheric debris injected into the high stratosphere of one hemisphere will produce high concentrations of the debris in ground level air in the other hemisphere in the spring 1 to 2 years later. These concentrations will then remain constant for about three years before beginning to decrease.

*Table V* shows the ^238^Pu/^239^Pu and ^238^Pu; ^239^Pu rations in Richland, Washington and at Pt. Barrow, Alaska. These data show how the ratio of 238Pu to 239Pu increased at these sampling stations as a result of debris from the SNAP-9 device. This ratio increased by more than an order of magnitude and was substantially higher at Pt. Barrow, 71° N, than at Richland, 46° N. These data would suggest interhemispheric circulation within the mesosphere may have an important factor in ^238^Pu transport toward the northern polar regions.

Although not directly formed in the nuclear weapons detonation, considerable if ^241^Am are present in fallout debris. This, of course, results from the decay of ^241^Pu. Based on the amount of ^239^Pu in the atmosphere and the ratio of 239Pu to ^241^Pu observed in the Ivy Mike test, one can calculate their approximate ratios as a function of time in the atmosphere. These ratios are plotted in *Figure 5* together with the observed concentrations of ^241^Am as measured from samples taken at our monitoring station in Richland, Washington. It is evident that the airborne concentrations are in reasonably good agreement with those which were calculated and that the ratio of ^241^Am to ^239-240^u does increase, as would be expected, as the debris ages. Based on the yields of transuranium elements which were observed in the Ivy Mike tests and the ^239-240^Pu inventory established by the HASL, the total amounts of the transuranium elements which have entered the atmosphere can be estimated. These values are shown in *Table IV*. For isotopes of mass greater than 244, the total atmospheric injections appear to be in the range of hundredths to ten of curies.

== Short-Lived Radionuclides in Fallout from Nuclear Weapons Testing

Nuclear debris from the past three Chinese tests has been examined to estimate the radiation exposure resulting from individual short-lived radioisotopes. A typical analysis of these short-lived radionuclides is shown in *Table VI**. It is evident from these data that the amounts of ^237^U (6.75 days) and ^239^Np (2.35 days) are very high compared with most of the short-lived fission products. It has been shown that these radionuclides will contribute a substantial fraction of the radiation exposure based on either submersion or the ground-deposited radiation.