[id="con_review_moist_mesoscale_models_{con-moist-models}"]
include::../attributes.adoc[]

A new area in the precipitation scavenging research program which has been initiated in the last few months is a review of presently existing moist mesoscale numerical models. This review has been undertaken to develop within the program a mesoscale model into which precipitation scavenging concepts in frontal storms may be integrated. The model formulation will not replace the field experiments, but act with the field experiments in a combined model-observational approach, each component dependent upon the other. The mesoscale is not the only scale involved in precipitation scavenging; the cloud and microphysical scales are also important and must be involved in the model formulation. With this in mind, some general objectives of the modeling program may be stated:

1. To isolate or identify those mechanisms most important in determining how much material will be placed on the surface. Controlled experiments with systematic variation of one parameter at a time allow the role of a particular parameter to be isolated. Bits and pieces of the scavenging process are understood, but individual components are so interrelated and complex that a model is needed for the integrated picture;

2. To indicate the type and location of critical field experiments, resulting in better-designed experiments, resulting in better-designed experiments. Field experiments are used, of course, for model verification. Following verification, a great variety of natural conditions may be examined at much lower cost than with many field experiments.

Benefits which might be realized from a mesoscale model, in particular, include:

1. The model could provide environmental conditions for a more detailed microphysical model incorporating precipitation scavenging calculations. These environmental parameters include horizontal wind speed, temperature, humidity, and mesoscale vertical motion at various levels in the atmosphere;

2. Such a model could provide information on changes in the large scale flow resulting from terrain-induced or land-sea induced horizontal and vertical air motion. Such information could be used to interpret the results of past field experiments;

3. The model could provide information to aid in planning future field experiments, such as supplying air motions in the frontal rain areas. Determinations might be made, for example, of whether tracer releases upwind of frontal rain bands might be incorporated into the cloud at various altitudes.

With regard to the latter usage, past tracer releases have been made within the rain-producing clouds of frontal storms. This is clearly unrealistic if one is concerned with the scavenging of pollutants by frontal rain, since the pollutant would have its source near the ground below cloud base in most cases and would be delivered to the cloud layer through cloud base by large-scale, forced lifting over large horizontal distances. In-cloud tracer releases are perhaps more realistic in experiments designed to simulate the scavenging of materials incorporated into the cloud above cloud base by horizontal motions relative to the cloud. However, even in this case, the three-dimensional distribution of tracer concentrations within the cloud resulting from an aircraft release may bear little resemblance to the distribution resulting from a plume of material converging upon a cloud due to the relative motions of the cloud and plume. This is not to say that experiments involving in-cloud tracer releases are without value; these experiments may yield relative suggestions (as opposed to absolute estimates) of what would occur as a result of variation of experimental parameters (e.g., hygroscopic versus non-hygroscopic tracer, variations in release height within the cloud, variation in tracer particle sizes) to simulate natural variations of material plumes. It would seem that a worthwhile goal of future field experiments, however, should be to strive for tracer releases outside the condensed cloud.

There is a potentially important role for the mesoscale model to play with regard to the above discussion. The model might be used, for instance, to simulate aircraft tracer releases and (with the incorporation of a microphysical sub-model) deposition fluxes, and to determine whether, in a release outside the rain cloud, sufficient tracer may be concentrated in the fallen rain to permit a meaningful analysis. There is also the possibility of using urban pollutants directly as the material to be scavenged by the frontal storms in field experiments and in the model, as has been done in a case study of scavenging by convective storms in the St. Louis urban areafootnote:1[C. E. Hane, "Scavenging of Urban Pollutants by Thunderstorm Rainfall: Numerical Experimentation," this volume.]. The model might be utilized in this frontal storm case to determine whether significant concentrations of pollutant exist in fallen precipitation (i.e., to aid in the planning of field experiments).

With these needs in mind, the following summary of mesoscale moist numerical models is presented. One model, or a modification thereof, will eventually be selected and utilized to satisfy as many as possible of the above needs existing within the scavenging program. In all, nine models were reviewed, including most (but probably not all) moist mesoscale models which have been formulated. The ordering of the models is done according to the temporal sequence in which they were located in the literature.

The table includes 16 bases for comparison for each of the 9 models. The superscript following the year in which the model was described in the literature (*Column 1*) refers to the numbering in the list of references.

The models may be categorized in a number of ways. An obvious difference, for instance, is in the horizontal scale or grid point separation, according to which, *Models 1 - 5* may be separated from 6-9. The vertical structure of most of the models is similar, with 6-12 constant height or constant pressure levels, with the exception of *Model 3*, which contains a single mixed layer with upper and lower fluxes supplied by boundary layers not governed directly by time-dependent equations. Also *Model 5* includes increased vertical resolution compared to the other models. The variables predicted in all of the models are for the most part the same: two horizontal wind components, pressure on constant height surfaces or height of constant pressure surfaces, temperature, water vapor, and vertical air motion (determined diagnostically). Another important criterion is the cost involved in running the model. These costs are very difficult to categorize since they vary over a wide spectrum; *Model 3* is least expensive to run since it is not completely {3D} and *Model 5* will be the most expensive when it reaches the final planned stage of development.

Judgments on the best model for the scavenging program are extremely preliminary; priorities have not been established at this time regarding the modeling needs of the scavenging program, nor have the resources available for the development and running of such a model has been established. Of the presently running models, *Model 1* seems most valuable to the scavenging program (especially if orographic effects are added) since the effects of convection embedded in the mesoscale environment are included in the model. However, the expenses involved in running *Model 1* are quite large. The possibility exists for using the history tapes from *Model 1* to provide a mesoscale framework within which to do scavenging calculations for panning purposes, etc.; however, to apply the model to past cases where scavenging field experiments have been done may not be financially feasible. *Model 1* has been used by Kreitzberg, Lutz, and Perkey to compute what they call "precipitation cleansing" or the time-integrated stable and convective precipitation passing through parcels whose {3D} trajectories are computed by the modelfootnote:12[C. W. Kreitzberg, M. Lutz and D. J. Perkey, "Precipitation Cleansing Computation in a Numerical Weather Prediction Model," Fate of Pollutants, John Wiley & Sons, Inc. (in press).]. Such a computation might be extended to include the details of the precipitation scavenging process in both convective and stable rainfall, as suggested by Perkeyfootnote:12[D. J. Perkey, personal communication, 1975.].

== Acknowledgement

I am most grateful to Bryan Scott for some very useful comments.