[id="con_estimate_in_cloud_scavenging_tracer_frontal_storms_{con-injected-frontal-storms}"]
include::../attributes.adoc[]
:stem: latexmath

== Introduction

Air pollution removal by precipitation is important as a cleansing agent for our airfootnote:1[R. J. Engelmann and W. G. N. Slinn, Precipitation Scavenging (1970), AEC Symposium Series, No. 22, 1970.]. One of the ways in which air pollution can be deposited in precipitation is the in-cloud scavenging of the pollution through cloud water and precipitation of picking up and removing pollution. These removal processes can occur in both convective storms and frontal storms. (For studies of the processes in convective storms, see Bursev, et al., 1968footnote:2[I. I. Burtsey, L. V. Bertseva and S. G. Malakhov, "Washout Characteristics of a 32^p Aerosol Injected into a Cloud," Atmospheric Scavenging of Radiosotopes, 242-250, 1968.], Dingle et al., 1968footnote:3[A. N. Dingle, D. F. Gatz and J. N. Winchester, "A Pilot Experiment Using Indium as Tracer in a Convective Storm," Journal of Applied Meteorology, 8:236-240, 1968.], Summers, 1972footnote:4[P. W. Summers, "The Silver Fallout Patterns in Precipitation from Seeded Convective Storms," in preprints, Third Conference of Weather Modification, Rapid City, SC, American Meteorological Society, 279-286, 1972.], Warburton, 1973footnote:5[J. A. Warburton, "The Distribution of Silver in Precipitation from Two Seeded Alberta Hailstorms," Journal of Applied Meteorology, 12:677-682, 1973.], and Young et al., 1974footnote:6[J. A. Young, T. M. Tanner, C. W. Thomas and N. A Wogman, "The Entrainment of Tracers Near the Sides of Convective Clouds," Pacific Northwest Laboratories Annual Report for 1973 to the USAEC Division of Biomedical and Environmental Research, Part 3, Atmospheric Sciences, BNWL-1850 PT 3, Battelle, Pacific Northwest Laboratories, 146-147, 1974.].) The study presented here was initiated to determine the effectiveness of these removal processes in frontal storms by the injection of a tracer, In, into frontal storms.

In-cloud scavenging has been studied through the building of a model that incorporates the in-cloud scavenging process, the removal and the deposition of air pollution in precipitationfootnote:7[K. P. Makhon’ko, Simplified Theoretical Notion of Contaminant Removal by Precipitation from the Atmosphere, Tellus, 19, 467, 1967.],footnote:8[W. E. Davis, "An Interpretation of the In-Cloud Scavenging of Particulates," Pacific Northwest Laboratory Annual Report for 1969 to the USAEC Division of Biology and Medicine, vol. 2, Physical Sciences, 1, Atmospheric Sciences, Battelle-Northwest, Richland, WA, pp. 107-110, 1970.],footnote:9[W. E. Davis, "A Model for In-Cloud Scavenging of Cosmogenic Radionuclides," Journal of Geophysical Research, 77, 2159, 1972.],footnote:10[A. N. Dingle and Yean Lee, "An Analysis of In-Cloud Scavenging," Journal of Applied Meteorology, 1295, 1975.]. The model results may be compared with observed deposition from the tracer injected into a rain-producing cloud during a frontal storm. This comparison permits an estimate to be made of the effectiveness of in-cloud scavenging in the removal process.

In the past 4 years, injections of a tracer, In, have been made into frontal storms near {quil}, {WA}, on the {OP}footnote:11[W. E. Davis and J. A. Young, “Results of In-Cloud Tracer Releases in Frontal Storms,” In Proceedings of Symposium, "Precipitation Scavenging - 1974," Champaign, IL (to be published - 1975).]. Here we attempt to compare a model’s computed deposition rates calculated from observed deposition patterns. The aim is to determine the effectiveness of in-cloud scavenging.

== Model

The model previously reported by Davisfootnote:8[],footnote:9[] was chosen because neither in-cloud measurements nor information concerning the tracer were detailed enough to permit use of the Dingle and Lee modelfootnote:10[]. The Davis model is based on a three-phase process. The first phase is the interaction of the tracer with the cloud water. In this case the transfer of material, In, from air to cloud water, will be referred to as in-cloud scavenging, stem:[\lambda]. The second phase, removal of In from the cloud water by rain or snow, will be referred to as dilution, stem:[\psi]. The third phase is the transfer of In by rain or snow to the ground.

For a detailed account of the model and assumptions, see *References 8 and 9*.

=== Case 1. March 11, 1971

Results of an analysis of surface deposition to compute a surface deposition have been reported by Davisfootnote:12[W. E. Davis, "Computer Results for an In-Cloud Release of In on 11 March 1971," Pacific Northwest Laboratory Annual Report for 1971 to USAEC Division of Biomedical and Environmental Research, Part 1, BNWL-1651, Battelle, Pacific Northwest Laboratories, 16-19, 1972.]. Only the comparison of the model curves with the calculated deposition rate will be reported.

In comparing the model’s curves with derived deposition rate curves (*Figure 1*), the curves that best approximate the derived curve are those with the in-cloud scavenging coefficient, stem:[\lambda] between stem:[10^{-2} \, sec^{-1} \, - \, 10^{-3} \, sec^{-1}]. Finer resolution is difficult since varying stem:[\lambda] and stem:[\psi] can produce the same deposition ratesfootnote:12[],footnote:13[W. G. N. Slinn, "Rate Limiting Aspects of In-Cloud Scavenging," Journal of Atmospheric Sciences, 31:1172-1173, 1974.]. Some limits to stem:[\psi] and stem:[\lambda] can be calculated. As shown in the figure, the curve with stem:[\psi \, = \, 2 \, \times \, 10^{-4} \, sec^{-1}] and stem:[\lambda \, \le \, 10^0 \, sec^{-1}] yields deposition rates lower than those needed to explain the calculated deposition rates. Therefore, one could conclude that stem:[\psi] is greater than stem:[2 \, \times \, 10^{-4} \, sec^{-1}]. An independent estimate of stem:[\psi] was madefootnote:14[D. G. Atkinson, W. E. Davis, L. F. Radke, B. C. Scott, W. G. N. Slinn, T. M. Tanner, J. M. Thorp, N. A. Wogman and J. A. Young, "Precipitation Scavenging of Tracers Released Into Frontal Storms," Pacific Northwest Laboratory Annual Report for 1971 to USAEC Division of Biomedical and Environmental Research, Part 1, BNWL-1651, PT 1, Battelle, Pacific Northwest Laboratories, pp. 16-19, 1972.] based on assuming as a constant a derived liquid water content of stem:[0.2 \, g/m^{3}] and a mean rate of rise as determined from aircraft and radiosonde data. The dilution coefficient ψ was computed to be stem:[4 \, \times \, 10^{-4} \, sec^{-1} \, - \, \sim{2} \, \times \, 10^{-3} \, sec^{-1}]. These values are greater than the minimum of stem:[2 \, \times \, 10^{-3} \, sec^{-1}] indicated in the modeling study, and are in the same range of values for stem:[\psi] which with stem:[\lambda] computed above would explain the calculated deposition rate.

=== Case II. December 5, 1973

Results of the analysis of surface deposition have been reported by Davis and Youngfootnote:11[]; only the comparison of the model’s curves and the calculated deposition rate will be reported.

The model curves which best approximate the derived curve out to the fourth arc are those with an in-cloud scavenging coefficient, stem:[\lambda] between stem:[10^{-4} \, sec^{-1} \, - \, 10^{-3} \, sec^{-1}]. The increase in deposition rate on the fifth arc could not be explained by the model. Also, as shown in the figure, the curve with stem:[\psi \, = \, 10^{-5} sec^{-1}] and stem:[\lambda \, \le \, 10^{0} \, sec^{-1}] yields deposition rates too low to explain the calculated deposition rates. Hence one could conclude that stem:[\psi], the removal of In in the cloud water by rain or snow, is greater than stem:{10^{-5} \, sec^{-1}].

An independent estimate of ψ was difficult, because no measurement of liquid water or temperature structure downwind of the release point was made during the test. An estimate of liquid water was made using the temperature at release point and the lapse rate together with observations of liquid water in frontal stormsfootnote:15[I. N. Ponomarenko and T. N. Zabolotskaia, Experimental Data on the Liquid-Water Content of Frontal Clouds over the Steppe Portion of the Ukraine, translated from Russian by the American Meteorological Society, 1965.] of stem:[\sim{0.30} \, g/m^{3}]. Two methods were used to estimate stem:[\psi]. The first took the change in height along the trajectory path as equal to the change in mean elevation as the parcel moved across the peninsula. The second was based on the mean  rise of the air parcel necessary to produce the observed precipitation. In both cases the liquid water content was assumed constant and the amount of water removed from the air parcel was assumed to be the excess above saturation. The resulting dilution coefficient was estimated at stem:[\sim{7} \, \times \, 10^{-4} \, sec^{-1}] for the second method. These values were greater than the minimum values estimated by the model of stem:[1 \, \times \, 10^{-5} \, sec^{-1}] and in the same range as those computed by the model. One should note that the observations of liquid water content in frontal storms, as reported by Ponomarenkofootnote:15[] did have a minimum of stem:[0.08 \, g/m^{3}] and a maximum of stem:[0.78 \, g/m^{3}]. This would extend the range of estimated stem:[\psi] dilution coefficient, from stem:[\sim{1} \, \times \, 10^{-4} \, sec^{-1} \, - \sim{3} \, \times \, 10^{-3} \, sec^{-1}]. Again these values are within the acceptable range of stem:[\psi] to explain the calculated deposition pattern.

=== Comparison of Case I and Case II

There are some definite differences in the two cases. First, the wind speeds varied from stem:[30 \, m/sec] in the March 11 case to stem:[22 \, m/sec] in the December 5 case. Also, the point of release although at the same altitude was made further to the south for *Case II*. The percent deposited was about the same, ~30% for March 11, 1971, versus 22-24% December 5, 1973. The wind speed and increase of distance produced a time of deposition of stem:[\sim{55} \, min] in the December 5 case, versus stem:[\sim{15} \, min] in the March 11 case. Thus, as one would expect, the rate of deposition for December 5 was less than that for March 11.

Both cases show increasing deposition rate with time. In the March 11 case, the last two of the three arcs crossed showed essentially the same rate deposition. In the case of December 5 the trend was toward increasing deposition with time except on *Arc 4* which showed a decrease. This trend toward increasing deposition is shown by curves in the model with stem:[\lambda] ranging from stem:[10^{-3} \, - \, 10^{-4} \, sec^{-1}].

The most interesting feature of either deposition is the increase of the December 5, 1973 case. The model could not account for this increase. When the estimated mean air mass rise was imposed, the tracer injected air parcel would have risen to a height where the temperature was stem:[\le \, 0 \circ C] before the time when removal would have deposited material on the fifth arc. It may be that the melting of falling snow and freezing of cloud droplets as well as the observed increase in the precipitation rate could have enhanced the removal rate. One should note that In released on March 11 was injected at stem:[\sim{0} \circ C \, - \, -1.5 \circ C] level at at a higher mean participation ratefootnote:14[], result in a higher calculated deposition rate.

== Discussion of Results and Conclusions

Two cases have been compared where In has been injected by flares into frontal storms. A range of values for in-cloud scavenging coefficients was determined for each storm with different results. For the March 11, 1971 storm a range of the in-cloud scavenging coefficient stem:[\lambda], of stem:[10^{-2} \, sec^{-1} \, - \, 10^{-3} \, sec^{-1}] was calculated between stem:[10^{-3} \, sec^{-1} \, - \, 10^{-4} \, sec^{-1}] for four of five arcs. The range of estimated stem:[\lambda]'s for the March 11, 1971 and December 5, 1973 cases were stem:[4 \, \times \, 10^{-4} \, sec^{-1} \, - \, \sim{2} \, \times \, 10^{-3} \, sec^{-1}] for March 11 and stem:[3 \, \times \, 10^{-4} \, sec^{-1} \, - \, 7 \, \times \, 10^{-4} sec^{-1}] for December 5.

Two measurements that can be compared are 1) the injection temperature of 2°C for the December 5 case versus stem:[-1.8 \circ C \, - \, 0 \circ C] for the March 11 case and 2) the mean precipitation rate of stem:[4. \, mm/hr \, - \, 5. \, mm/hr] for the March 11 case versus stem:[0.7 \, mm/hr \, - \, 2. \, mm/hr] for the December 5 case. The possibility exists that the freezing and melting process as well as the increased precipitation rate could have enhanced In removal. It is suggested that more work with additional in-cloud measurements be done in order to test this suggestion.

Dingle and Leefootnote:10[], as a result of their model studies, found agreement with Makhon’kofootnote:7[] and Davisfootnote:9[] estimates of the in-cloud scavenging coefficient (designated the diffusive attachment rate between particles and droplets by Dingle and Lee) and the dilution coefficient (designed the rate of accretion of droplets by raindrops by Dingle and Lee). The values they arrive at by a modelfootnote:10[] were for stem:[\lambda], stem:[10^{-5} \, - \, 10^{-4} \, sec^{-1}], and for stem:[\psi], stem:[10^{-4} \, - \, 10^{-3} \, sec^{-1}]. Davisfootnote:12[] indicated values of stem:[\lambda \, \le \, 10^{-4} \, sec^{-1}]. Makhon’kofootnote:7[] indicated a value of stem:[\psi] ranging from stem:[0.4 \, \times \, 10^{-4} \, sec^{-1} \, - \, 22 \, \times \, 10^{-4} \, sec^{-1}]. Based on the values reported by Rakhon’ko an incloud-scavenging co-efficient was calculated from stem:[3 \, \times \, 10^{-5} \, sec^{-1}] for stem:[Ra] - stem:[2.2 \, \times \, 10^{-3} \, sec^{-1}] for dissolved inorganic contaminant. The results of the analysis indicate that the value for stem:[\lambda] in the case of In may extend higher than the values arrived at by Dingle and Leefootnote:10[] and the computed values from Makhon’ko, with stem:[\lambda] as great as stem:[10^{-2} \, sec^{-1}] for the March 11 case.

Considerable caution should be taken in view of the assumptions that were made. Also, these values should be considered preliminary because of the lack of sufficient in-cloud measurements. Other tests should be made with will include not only sequential sampling at the surface but in-cloud measurements of liquid water, cloud drops sizes, ice crystal types, temperature and wind speed. Additional efforts should be made to size the tracer particles from the In flares. With these additional measurements it may be possible to arrive at a conclusive explanation for the difference in the in-cloud scavenging coefficient stem:[\lambda], stem:[10^{-3} \, - \, 10^{-2} \, sec^{-1}] for the December 5, 1973 case versus the stem:[\lambda] of stem:[10^{-4} \, - \, 10^{-3} \, sec^{-1}] for the March 11, 1971 case.

NOTE: The tracer _In_ is shorthand for _Indium_.