_The successes and shortcomings of the 1972-73 series of multiple tracer releases are reviewed. Tracers were dispersed to the atmosphere simultaneously from an elevation of 26 m. Although the particulate tracer, zinc sulfide, showed strong evidence of depletion in the near-ground layers, problems in calibration of the racer assay technique complicates the specification of the magnitude of this depletion. Estimation of the zinc sulfide deposition was accomplished through comparison with the non-depositing, inert gas tracer, krypton-85. The krypton displayed strong evidence of “reflection” from the ground on one of the three experiments examined. The density of vertical samplers on the field measurement grid is currently not great enough to permit mass balance computation of high confidence. Following release into an unstable atmosphere, about 1% of the particulate zinc sulfide is estimated to have deposited before the plume reached 200 m. During one release into a stable atmosphere, 0 to 1% of the tracer deposited during movement to 812 m. During release into a somewhat less stable atmosphere, from 3 to 6% of the particulate zinc sulfide was deposited during transversal to 842 m._

== Introduction

The prime purpose of the series of tracer field releases carried out on the Hanford field diffusion grid during the thirteen months period beginning in October 1972 was to make measurements which would permit the estimates of deposition from particulate plumes. Analysis of the field results available to date does not justify [unreadable] the way of a firm quantitative description of particulate plume depletion due to contact with the ground and vegetative surfaces.

However, evidence suggests that the approach of this investigation holds promise of success. The main purpose of this note is to present this evidence and to present a minor amount of information on the magnitude of particulate plume depletion.

The field technique employed entails the simultaneous release of an inert gas, krypton-85, and one or more particulate tracers from the same location. The downwind air concentrations of the depleting particulate plumes are compared with concentrations of the depleting particulate plumes are compared with concentrations of the nondepleting krypton. The expected deficit of the particulates can be ascribed to deposition and other unspecified depleting mechanisms which occur primarily at the earth-air interface. One admitted difficulty with this technique is that measurement and analysis procedures which may be perfectly adequate for atmospheric diffusion studies may lack the accuracy and precision required in detection of (potentially) small differences in concentration. The adequacy of the currently used field tracer techniques is also considered in this report.

== Field Grid and Experiments

The multitracer field approach has several logistic or practical restrictions when contrasted with more conventional singer tracer diffusion studies. It requires simultaneity dispersion and sampling for the number of tracers involved hence additional manpower. Further, if the field sampling grids for the various tracers do not extend over the same range, the frequency of opportunity of field experiments is limited by the restrictions imposed by the smallest grid. In the current situation, the krypton sampling grid, with its relatively sophisticated but limited array of samplers, dictates a lesser range of wind directions acceptable for field experiments than would be permissible with the particulate sampling grid.

During the seventeen times the multi-grid system was activated during the current test series, weather and equipment “cooperated” sufficiently to justify actual tracer releases on eight occasions. All releases were from the 26-m elevation on the Hanford 122-m meteorology tower. Test identification, tracer released, and some pertinent meteorology are listed in *Table 1*. Abbreviations employed in this text to identify specific tracers are footnoted at the bottom of *Table 1*.

Field sampling for the particulates took place on filters placed on a grid of sectors of six arcs concentric (or nearly so) about the tracer release tower. The angle embraced by the sampling arcs was approximately 80°. The basic sampling elevation was 1.5 m. Distances of the sampling arcs from the release point were approximately 0.2, 0.4, 0.8, 1.2, 1.6 and 3.2 km footnote:[Arcs at 0.8, 1.6 and 3.2 km are actually concentric about a point 100 m due south of the release point. Thus the distance from release point to arc varies with azimuth.]. Additionally five towers spaced at 8° increments were found on each of the arcs at 0.2, 0.8, 1.6, and 3.2 km. Samplers on these towers reached elevations of 33, 42, 62 and 62 m, respectively. Vacuum for sampling was supplied by pumps powered by small internal combustion engines.

The grid instrumented with 127 krypton-85 detectors was restricted to three arcs. Basic sampling level again was at a height of 1.5 m. The azimuths embraced by krypton detectors were 58, 40, 15° at 0.2, 0.8 and 1.6 km respectively. Tower mounted detectors were operative only at 0.2 and 0.8 km.

Vertical profiles of wind speed, wind direction and temperature were measured on the 122-m tower at the source point and on a nearly 24-m tower.

== Data Reduction

The two field sample assay techniques felt to be best “in hand” at the onset of this test series were for FP^(1)^ and Kr.^(2,3)^. All filters from each of the eight experiments have been assayed for FP. However, the assay procedure used was one developed about 13 years ago. It is now seen that to attain the more accurate mass measurement required by this test series, the FP assay procedure is in need of refinement and that the Rankin counter used in assay is in need of recalibration. Steps are currently underway to effect these improvements. Once they are completed, all filters will be reassayed for FP.

Two have distributed the smooth reduction of the Kr measurements. The first involved a malfunction of a tape recording system during the four 1972 tests. The result of the intersection of a considerable number of spurious signals between or over meaningful Kr concentration measurements. A long and frustrating iterative process of editing tape output, reprogramming, and generating new output has only recently resulted in the retrieval of a complete set of valid for test V2. Indications are that a similar approach will obtain valid V1 data. However, retrieval of Kr data from tests V3 and V4 is in considerably greater doubt.

The second problem with Kr data involved possible faulty control of a high voltage. This may have caused a reduction in Kr detector count rate (and resultant indicated concentrations of Kr) during some periods of field operation. A careful examination of operational notes during field experiments and of accompanying background count rates may permit diagnosis of the samplers affected and of the magnitude of the effect.

Since the analysis of a filter of rhodamine is a destructive assay technique it will be delayed until after the filters are reassayed for FP. (The FP assay is nondestructive.) Although our chemists feel that filter assay for indium will be feasible, the specific procedure has not yet been developed.

For completeness, *Table 1* lists all eight field tests in the current series. However, the analysis and discussion which follow result from Kr and FP measurements made during field tests V5, V6, and V7 only. As mentioned earlier, recording problems have precluded the decoding of Kr measurements from tests V1 through V4. (The valid Kr data from test V2 became available too late for inclusion in this report.) Since it was raining at the onset of test V8, it was decided not to chance exposing the krypton system to Gieger-Müller detectors during that experiment.

== Analysis and Discussion

Despite awareness of the limitations imposed by calibration  uncertainties, a mass balance was attempted on tracer passing the 200 and 842-m arcs during test V6. This test was selected since all tracers (above the 1.5-m elevation) were contained within the crosswind dimension (y) delineated by live towers on each arc. The procedure entailed specification of normalized exposures (E/Q, with units of sec/m^3^) at all measurement points on the vertical surface. Isopleths of E/Q were then drawn on the basis of these data points. *Figures 1 and 2* show isopleths of E/Q at 842 m for Kr and for FP. The dashed isopleths are extrapolations above the tops of the 42-m towers.	

After isoplething, a value of E/Q was interpolated for each box in a grid with dimension of one meter in height (z) and one degree in crosswind width. The interpolated E/Q values were summed crosswind and multiplied by their crosswind spacing increment (Δy, with units of meters) to obtain crosswind integrated exposures (CIE/Q, with units of sec/m^2^). Examination of vertical wind profiles measured during tracer release provided wind speeds (ū, with units of m/sec) which, when multiplied by 100 (CIE/Q) of tracer passing through the vertical surface per meter increment increase in height (P, with units of %/m).

It is obvious from a cursory examination of the isopleths on *Figures 1 and 2*, that the exposure of FP are considerably greater than those for Kr. This fact is reflected by the summation of P over all levels. This sum (∑, with units of %) will total 100% for a perfect mass balance. At 842 m for test V6, ∑~Kr~ = 37% and ∑~FP~ = 133%. Although the graphics are not presented for the similar procedures performed at the 200-m arc, the sums found there are ∑~KR~ = 57% and ∑~FP~ = 198%.

There are several potential reasons for the large discrepancy from the ideal. As has already been mentioned, a miscalibration in assay technique is one possibility. Mismeasurement of the amount of tracer dispersed is another. Poor isoplething (whether due to incompetence or paucity of data points) is a third possibility. Mismeasurement of the wind speed profile could introduce an error, though hardly one of the magnitude displayed.

In any event, if it is presumed that the measurements made of tracer concentration were correct in a relative sense (as opposed to absolute), the percentages actually observed can be normalized to total to 100%, and the vertical profiles of Kr and FP can be compared. This normalization procedure led to the profiles shown on *Figure 3*. Here there is reasonable agreement between tracers. Cumulatively summing tracers from the ground level upward reveals 50% of the tracer below 25.6 m for both Kr and FP at the 200-m arc. At 842 m, the fiftieth percentile is reached at 24.8 m for the Kr and at 24.2 for the FP. Extrapolation above tops of the towers at 200 m accounted for 18% of the Kr and for 14% of the FP. At 842 m above-tower measurements accounted for 10% of the math in both cases.

Probably the most encouraging point made on *Figure 3* is the increase in Kr percentage observed in the lowest 5 m of the 842-m curve. This increase is very likely due to the (so-called) reflection from the ground of inert gas. Contrast this increase with the sharp decrease in percentage of the particulate FP in the lowest 5 m. This contrast in near ground-level exposures is also evident in the examination of *Figures 1 and 2*. These differences suggest strongly that the experimental approach has good chance of success if the mass or concentration can be better quantized.

Although the isoplething and subsequent computations of tracer per unit increment in elevation are amenable to computer processing, the results presented above were tediously generated by hand. The question arises as to how much better is this careful approach than a more simple, quick-and-dirty (QAD) approach. Hence, for test V6, the fraction of tracer per meter of elevation was computed for the seven Kr measurement levels and for the 17 or 18 FP measurement levels. Here only five data points were used for computing the crosswind integrated exposures. (In test V6, the end data points were zero since no tracer was observed on the towers at the extremities of the crosswind distribution.) The vertical profiles generated from this QAD approach are shown by the solid curves on *Figure 4*. No extrapolations were made above the tops of the towers. The current calibrations (miscalibrations?) for determining Kr and FP were used. By weighing the proportion of the total tracer by the vertical spacing of data measurement points, the total tracer passing each are - up to the top measurement level - could be computed. These sums are indicated at the appropriate elevations on *Figure 4*. 

The individual dots and X’s plotted on *Figure 4* are those generated by the careful isoplething approach. (The values plotted here were not normalized to force a total of 100%.) The close agreement in the profiles suggests that the effort involved in the detailed approach was largely wasted.

The QAD approach was also used in the computation of profiles of tracer for tests V5 and V7. Since the tracer plumes were not contained crosswind within the bounds of the towers on tests V5 and V7, some estimates of the proportion of the tracer outside these bounds was required. The only hint of this proportion was afforded by the basic 1.5-m samplers on the FP grid. (The Kr grid at 1.5 m did not encompass the crosswind tracer distributions.) Estimates of tracer beyond that represented by the dower grid during test V5 were 25% at 200 m and 43% at 812 m. Corresponding values during test V7 were 51% and 47% for 200 m and 867 m respectively. As mentioned earlier, the percentages were zero for both 200 m and 842 m during test V6.

The amount of tracer within bounds of the towers was corrected for that estimated to be beyond, and the results are plotted on *Figures 5, 6, and 7*. The figures at the top of each curve are sums of tracer percentage up to that topmost measurement point. Plotting the percentages on a logarithmic scale emphasizes that with the exception of the lowest 5 m or so, the profiles for Kr and FP are reasonably parallel. If attention is restricted to the curves above 5, the implication is that although calibrations used in generating either or both curves were in error, the ratio of indicated Kr to indicated FP was consistent. Thus the individual curves are likely valid in a relative sense. If the FP and Kr curves can be superimposed so that the one essentially overlies the other in the 5-m-and-above elevations, the discrepancies between the curves below 5 m can be used to investigate the effects of deposition.

Before proceeding with the deposition investigation, another point can be made regarding relative agreement of the Kr and FP data. *Table 2* presents the ratio of the computed sums of Kr to that for FP by test and sampling arc. There is little variation from sampling arc to sampling arc in this ratio (0.64 to 0.60 for test V5 for instance), although there is considerable variation in the amount of tracer computed as passing the arcs (87% to 132% for ∑FP on test V5, for instance). The implication here is that the calibrations for FP and Kr are consistent for a specific test, but that the large differences in the total mass computed as passing different arcs during the same tests are due to insufficient sampling density. It is recognized that the somewhat different fractions of the plumes can be above the tops of the towers, but in the stable atmospheres observed during tests V5 and V6 the bulk of the tracer should have remained below the tops of the towers. Furthermore, the isoplethed percentages listed in *Table 2* for test V6 include extrapolations to embrace the entire vertical distributions, and here also the ratios remain conservative while the percentages vary.

Estimates of the fraction of FP tracer depleted from the plums have been made graphically for three locations: test V5 at 812 m, test V6 at 842 m, and test V7 at 200 m. Tracer concentrations were too near background to consider analysis in the other three possible cases (V5 and V6 at 200 m, and V7 at 867 m). The appropriate Kr profiles of *Figures 5, 6, and 7* were extrapolated [illegible] to zero, and the summed percentages under these curves were normalized to 100%. Then, on the basis of the relatively constant FP to Kr mass ratios above 5 m (where deletion effects were missing or less significant), the FP profiles were normalized to match the general profile of the Kr. Thus the areas of the curves above 5 m should total to the same value.

The lower portions of these profiles are displayed on *Figure 8*. Since test V6 shows the most dramatic depletion, it will be used to illustrate the graphic approach employed. The solid curves are previously described normalized profiles of Kr and FP percentage. The deficiency of FP in the lowest 5 m is proportional to the area ABC less area DEB. This converts to 2.8% of the tracer depleted during the plume traversal to the 842-m area.

An alternative approach is to presume that the shape of the FP profile below 5 m would have been that of the Kr profile had deposition not occurred. The area describing depletion then becomes AEF, and this area corresponds to a 5.7% depletion.

The same approach was employed for tests V5 and V7. The range of estimates of depletion are given in *Table 3*.

An aerial plot of FP exposures based on measurements made at the 1.5-m level could be employed with the deposition estimates presented, and estimates of deposition velocity could be developed. However, the confidence in the absolute value of the measurements currently reported does not justify the effort.

If a complete mass balance is to be attempted following future field experiments, the evidence presented suggests that a much more dense sampling network than that currently in use is needed. To “fill in” the holes with many more towers and samplers becomes impractical from budgetary and manpower considerations. Presuming high confidence in the accuracy of tracer concentration measurements can be attained, the compromise of comparison of tracers within a restricted but intensely instrumented grid offers possibilities. For instance, a relatively low-elevation aloft release during stable atmospheres might be instrumented only up to the level of release with the assumption made that a “half-mass” balance would be performed.

== Conclusions

The field measurement techniques currently employed for Kr and FP produce good relative concentrations of these tracers, but better definition of absolute concentrations is required in deposition studies. Better calibration of the measurement techniques is in order.

For the field experiment examined in the greatest detail (test V6), the median deviation for the mass of tracer passing arcs at 200 and 800 m from the source is within 2 m of the release height of 26 m.

In all three field experiments examined, at distances where significant amounts of tracer intersected the ground, the vertical profiles showed an increase of the FP tracer with respect to the KR at elevations near the ground. Test V6 displayed strong evidence of reflection from the ground by the inert gas.

The density of field sampling at elevations above 1.5 m preclude confident mass balance computations. Careful isoplething of exposures and subsequent crosswind summing of mass by small vertical increments gave small differences when compared to a more gross “quick-and-dirty” crosswind summing approach.

Following release into the unstable atmosphere of test V7, about 1% of the released FP tracer is estimated to have been deposited before the plume traversed a distance of 200 m. During a release into a quite stable atmosphere 0 to 1% of the tracer was deposited during plume traversal to 812 m; and during release into a somewhat less stable atmosphere, 3 to 6% of the tracer was deposited during traversal to 842 m.