[id="con_scavenging_thunderstorm_{con-scavenging-thunderstorm}"]
include::../attributes.adoc[]
:stem: latexmath

== Introduction

It is well known that high concentrations of pollutants are at times found in the lower atmosphere in the immediate vicinity of large urban areas. It is less well known that rainfall can quite efficiently remove pollutants from the urban atmosphere. It is reasonable to suppose that the highest removal efficiencies are achieved by well-organized thunderstorms, whose structure is such that low-level pollutant-bearing air is quickly delivered to the region of the storm where water vapor is condensing, and subsequently travels to the rain formation region. These storms may be contrasted in their scavenging efficiency with rain from clouds produced by large-scale forced lifting (e.g., midaltitude extratropical cyclones), where the pollutant is either removed by falling rain below the clouds (a much less efficient process) or by rising very slowly over large horizontal distances to reach regions of condensation. Each of the latter processes would result in much smaller fluxes of pollutant in rain to the ground than in the case of squall lines, thunderstorm clusters, or large isolated thunderstorms. The research here seeks to understand how much and where pollutant is deposited on the ground as a result of thunderstorm passage through an urban pollutant plume.

== Model Application

A {2D} time-dependent thunderstorm numerical model has been used to produce a realistic thunderstorm circulation using the environmental present in the St. Louis area on August 21, 1972. A steady state is assumed for the storm for the purpose of including precipitation scavenging calculations, utilizing the fields of motion and rainwater mixing ratio at one of the more intense stages during the storm's evolution. For a description of 1) environmental conditions on this day, 2) the storm evolution, and 3) storm structure during the assumed steady-state period, the reader is referred to an earlier paperfootnote:1[C. E. Hane, "Precipitation Scavenging in a Small Line: Numerical Experimentation," PNL Annual Report for 1974 to the USAEC DBER, Part 3, Atmospheric Sciences, BNWL-1950 PT 3, pp. 143-149, Battelle-Northwest, Richland, WA, available from NTIS, Springfield, VA, 1975.]. The model itself is described in yet another paperfootnote:2[C. E. Hane, "The Squall Line Thunderstorm: Numerical Experimentation," Journal of Atmospheric Sciences, vol. 30, 1973, pp. 1672-1690.]. Previously reported resultsfootnote:1[] indicate that 1) in the absence of precipitation scavenging a significant portion of the pollutant is transported to the upper troposphere, and 2) the amount of pollutant reaching the region of the storm containing heavy rain has a significant dependence upon the vertical profile of pollutant concentration in the low-level air, which is the source of energy for the updraft. In particular, a pollutant with maximum concentration near the ground is more efficiently transported to the heavy rain region than one whose maximum concentration is aloft.

Here, the pollutant is allowed to enter the rainwater via a single process. The following assumptions are made:

1. All pollutant entering the cloud base is immediately incorporated into cloud droplets.

2. The pollutant enters the rain (rain is defined as liquid water moving with a velocity different than the air velocity) when the cloud droplets are accreted by rain.

3. Diffusion of the pollutant is neglected.

4. Evaporation of rain containing pollutant is accounted for only on the boundary of the rain area.

5. Chemical transformation of the pollutant is neglected.

6. Pollutant located where rainwater exists but cloudwater does not (a rare situation) is accreted at the same rate as if it were in cloudwater.

The incorporation of pollutant in cloudwater into rainwater is accomplished through accretion, represented by the following term:

[latexmath]
++++
(\frac{dq}{dt}_s) \; = \; Ec{\rho} \; Q/{\lambda}^{3.5}
++++

where stem:[c \, = \, 3.08 \, \times \, 10^{2}] is a dimensioned constant and stem:[\lambda \, = \, (2.51 \, \times \, 10^{}/q_{\ell})^{1/4}]. In the above expression stem:[q] is the pollutant-in-rainwater mixing ratio, stem:[E] is the collection efficiency, stem:[\rho] is air density stem:[Q] is the pollutant-in-cloudwater mixing ratio and stem:[q_{\ell}] is the midpoint of the trajectories of pollutant-bearing cloudwater and pollutant-bearing rainwater in the Lagrangian type scheme which is used for the time integrations. The term adds pollutant to the rain and reduces the cloud bearing pollutant at a given point, but by differing amounts, since in general the rain and cloud at a given point arrive along different trajectories.

== Model Results

A number of cases were run, including variations in the initial vertical distribution of pollutant. These runs are summarized *Table 1*. In each case the pollutant is initially distributed in the lowest stem:[2.4 \, km] of the atmosphere in a location such that it would begin to enter the cloud updraft region a few minutes later. The pollutant continues to enter through the boundary for a length of time corresponding to an urban plume with a horizontal extent of approximating stem:[22 \, km]. Each case was run for _2 hr_ model time with pollutant entering through the boundary for the first _45 min_. This is shown in *Figure 1* where the pollutant in air or cloud distribution, pollutant in rain distribution, and the cloud outline are contoured at four different times (stem:[10], stem:[30], stem:[50], stem:[70 \, min]) in the vertical cross section. The cloud outline is scalloped, the pollutant in air or cloud mixing ratio isolines (contour interval stem:[= \, 2.5 \, \times \, 10^{-8} \, g/g]) are solid, and the pollutant in rain mixing ratio isolines are dashed.

At _10 min_ (*Figure 1a*) the pollutant is transported into the cloud by the updraft, and the pollutant within the cloud (assumed to be in cloud droplets) is accreted by falling rain, as can be seen along the left edge of the cloud. At _30 min_ (*Figure 1b*) the pollutant can be seen to be reaching the ground in the rainfall. The pollutant in rain is also spreading upward for one of two reasons: 1) the pollutant is contained within drops whose terminal fallspeed is less than the upward air speed or 2) the pollutant is entering the rain at higher levels (the zero contour for pollutant quantities is not drawn). At _50_ and _70 min_ the upward spread is very similar. A quasi-steady state distribution would be achieved except that the urban pollutant enters the cloud after _80_ to _90 min_. After the times shown, the pollutant ceases to be carried to the ground; it remains in the rain in the upper portion of the cloud.

The pollutant-in-air maximum found in low levels to the left of the rain area results from evaporation of rain containing pollutant. This maximum is thought to be exaggerated in these experiments because a time was chosen for the steady-state motion and assumed rainwater fields when very little rain was reaching the ground, although a larger amount of rain was present higher in the cloud. This means that the pollutant in rain, as it approaches the ground, decelerates and travels more than it would when the rainwater mixing ratio near the ground was larger. This factor, then, leads to a slight underestimation of the deposition of pollutant on the ground.

In each case a pollutant budget was computed as a function of time accounting for the following: total pollutant in rain (*P1*) in the {2D} slab per meter slab thickness; total pollutant in air or cloud (*P2*); cumulative influx minus efflux of pollutant (*P3*); and cumulative deposition of pollutant in rain on the ground (*P4*). If *P5* represents represents the amount of pollutant present initially then the following balance is required

.Equation 1
[latexmath]
++++
P5 \; + \; P3 \; = \; P1 \; + \; P2 \; + \; P4
++++

An error was also computed as a function of time, defined by the right hand side of *Eq. (1)* minus the left hand side. The result of budget calculations for *Case C* are shown in *Figure 2*. The cut-off of inflow at _45 min_ is evident in the curve representing inflow through the boundaries minus outflow. This cutoff has a direct effect upon the pollutant-in-air concentration, which decreases rapidly from _45_ to _75 min_ when the peak pollutant in rain concentration occurs. The deposition on the ground (cumulative) increases steadily from _15 min_ until _75 min_. After this the accumulation time is slower, due to a lesser amount of pollutant in the rain. The error (numerical due to the finite differencing) is small at most times compared to other budget quantities, and certainly does not obscure the important processes. The budget results for other cases (not shown) are quite similar. The error in other cases is slightly larger, indicating that the error very likely results from finite difference inaccuracies in computing the flux through the lateral boundary at the surface level (since surface level lateral fluxes are larger in other cases) rather than inaccuracies in the internal computations.

The deposition of pollutant in rain as a function of downstorm distance was also calculated and is shown in *Figure 3* for all four cases. It is clear that the largest deposition occurs when the pollutant is concentrated near the ground, rather than concentrated at higher levels in the environmental air. This is because the air near the ground enters the heavy rain area of the cloud more directly than does the air at higher levels in the inflow region. The location of the urban plume relative to the deposition pattern is also shown. The deposition pattern is skewed with maximum deposition stem:[5 \,- \, 10 \, km] downstorm from the middle of the urban plume. This skewness is due to the polltant being carried by the storm for some time before being deposited on the ground. In addition, the pollutant bearing air has a component of motion opposite to the direction of storm motion. This air conserves part of that momentum as it travels through the storm so that the same pollutant can be deposited upstorm from the point where it entered the storm. This combination of factors results in the pollutant being deposited over a distance which is approximately twice that across the urban plume. The curve representing *Case B* shows the result for a run where the collection efficiency was reduced by a factor of ten compared to *Case A*. The cumulative deposition of *Case A* is only slightly more than twice that in *Case B* despite this change. This lower value of the collection efficiency of rain was used to crudely indicate what sort of changes would occur if some of the pollutant entering the cloud were not contained within cloud droplets. As can be seen a significant amount of deposition occurs in this case.

== Comparison with Observations

An attempt was made to compare the model deposition with the deposition of several pollutants measured for this stormfootnote:3[M. T. Dana, J. M. Hales, C. E. Hane, and J. M. Thorp, "Precipitation Scavenging of Inorganic Pollutants from Metropolitan Sources," Contribution EPA-650-3-74-006 in Ecological Research Series of the Office of Research and Development, U.S. Environmental Protection Agency, Washington, DC, June 1974.] in St. Louis, precipitation was collected and analyzed at only two downstorm distances, and 2) no data are available for air concentrations of pollutants for model input. Therefore only two observed points will be compared and air concentrations used for model input will be based upon average values for East St. Louis, {IL}footnote:4[Air Quality Data for 1968, U.S. Environmental Projection Agency, Research Triangle Park, North Carolina, APTD-0978, August 1972].

The speed of the storm in question was calculated from radar observations over a _90-min_ period to be approximately stem:[6 m/sec]. The storm speed resulting from model computations also was computed to be approximately stem:[6 m/sec]. The intensity of the model storm was, of course, time invariant, since a steady state was assumed. The actual storm, however, fluctuated in intensity as can be ascertained from the rainfall pattern (see *Reference 3*, *Figure 20*). Deposition from the actual storm at two downstorm points is listed in *Table 2*. These "points" are actually the average of values at 7 and 6 cross-storm collection sites along arcs approximately stem:[27] and stem:[45 km], respectively, from the NWS radar at Lambert Field (*Reference 3*, *Figure 20*).

The model results were obtained for a particular initial pollution-in-air concentration which averaged stem:[0.17 \, \times \, 10^{-6} \, g/g] for the stem:[2.2 km] layer near the surface. The cumulative deposition, as it turns out, is directly proportional to this initial air concentration in the model, for a given initial vertical distribution of pollutant. Accordingly, the numbers in *Table 2* may be adjusted for comparison with the calculated curve by multiplying the values by the ratio of model initial air concentration to observed air concentration. These adjusted values are also shown in *Table 2*. The other factor which must be estimated before a comparison can be made is the downstorm location to the urban plume on the day in question. No observations of this plume position are available on this day. So that a comparison might be made, the plume center was assumed to be along the {MS-R} or approximately stem:[17.5 km] toward the {se} from Lambert Field. The sampling sites as a result of this assumption were located at stem:[9.5] and stem:[27.5 km] from the plume center, as shown in *Figure 4*. This figure compares the deposited amounts at these two distances with the calculated amounts. The agreement is quite encouraging at *Site 1* except for the stem:[SO_\overline{\overline{4}}] which is calculated to be higher than observed by a factor of stem:[4]; at *Site 2* all observed values are slightly higher than calculated. It is quite possible that these observations at *Site 2* represent deposition of a significant amount of "background" pollution rather than urban pollution. Inclusion of "background" pollution in the model input would have produced closer aggreement at *Site 2*. In the author's opinion it is not worthwhile to speculate further upon the reasons for differences between calculated and observed, due to the overwhelming and obvious need for pollutant air concentration measurements prior to thunderstorm passage over the city in connection with such field programs.

== Conclusions and Recommendations

1. Organized convective storm structure is such that urban pollutant enters such storms with very high efficiency. The model calculations indicate that a significant fraction of this pollutant is scavenged by these storms, given that the pollutant becomes incorporated in cloudwater upon entering the storm. In *Case D*, approximately 80% of the pollutant entering the storm is deposited.

2. Comparison of observed and calculated pollutant depositions indicates that the model is predicting the amounts and downstorm locations of deposition with very reasonable accuracy, but additional observations are needed.

3. Pollutant deposition in rain is secondarily influenced by the vertical profile of pollutants in the pre-storm environment. The variation in cumulative deposition is on the order of 10-20% of the mean as a result of variation in vertical distribution.

4. There exists an overwhelming need to measure pollutant concentrations in the pre-storm environment in connection with future precipitation scavenging field experiments, such as those discussed in *Reference 3*. Each individual pollutant measured in rainfall should be measured in the air also. There is also a need for more downstorm precipitation sampling locations, including within the city, if possible. 

5. After running improved field experiments and model verification and improvement, a much simpler model could and should be formulated to provide such information such as 1) the aerial distribution of long term deposition of pollutants surrounding in an urban area and 2) maximum short-term doses of pollutant in rainfall. This information would be of great importance to problems in areas of agriculture, water pollution, city planning, and regional and global air pollution.