[id="con_growth_aerosol_urban_plume_{con-growth-aerosol-urban-plume}"]
include::../attributes.adoc[]
:stem: latexmath

== Introduction

The objective of the experiment conducted in St. Louis during the summer of 1975, was to determine the physical and chemical changes of pollutant in the city plume. Emphasis was placed on particle growth by coagulation and/or gas-to-particle transformation. The investigation was carried out using an instrumented {dc3}. The air parcel trajectory was identified by the movement of a stem:[0.94 m^3] tetroon by the movement of a ground to an altitude within the plume. Portions of the data will be represented here; details of the results will be reported later.

== Equipment

Size distribution of particles with diameters in the range of stem:[0.01 \, - \, 1.0 \, mu m] was measured within an airborne Electric Aerosol Analyzerfootnote:1[B. Y. H. Liu, K. T. Whitby, and D. Y. H. Pui, "A Portable Electric Analyzer for Size Distribution Measurement of Submicron Aerosols," APCA Journal, Vol. 24, 1067-1072, 1974], and those from stem:[0.3 \, \mu m] to about stem:[5 \, \mu m] were obtained with a {royco-mon} interfaced with a {15-chan}. A {gen-count} was used to measure concentrations of Aitken nuclei. Particles were also collected on IPC filters at the rate of stem:[50 \, cfm] for later chemical analysis. A flame photometric detector was used to determine SO~2~ concentration. NO, NO~2~ and O~3~ concentrations were measured with a {teco}, NO~x~ analyzer, and a {bendix}. Dew point, and aircraft parameters were also recorded. Most of the parameters were also recorded. Most of the parameters were sampled 5 times per second, and averaged over the second via a Nova computer and stored on a {7track-r}.

== Sampling

The tetroon was launched either from {cair} or {wair}, located at the edge of the city (see *Figure 1*), depending on the wind direction. The location was chosen to prevent the tetroon from going over the city and interfering with commercial aircraft flights. The procedure for deploying the tetroon is that described by Hoeckerfootnote:2[W. H. Hoecker, “A Universal Procedure for Developing Constant-Volume Balloon and for Deriving Vertical Air Speed from Them,” Journal of Applied Meteorology, Vol. 14, 1118-1124, 1975.]. Before and during each flight, pibal data were collected to determine wind speed and direction. The tetroon was launched 1 hr after the aircraft took off to allow instrumentation calibration and stabilization.

On August 6, a tetroon was launched at 1615 local time from {wair} to an altitude of stem:[3000 \, ft \, MSL]. The day was characterized by low overcast stratus and stratacumulus in the morning changing to broken cumulus by noon, then broken variable scattered cumulus and swelling cumulus in the afternoon; clear at sunset. The wind was from the northeast at about stem:[17 \, knots]. The temperature inversion at 1647 hr was located at about stem:[8000 \, ft \, MSL]. Although SO~2~ data was not collected during this flight, values of stem:[48-93 \, ppb] were measured at stem:[3000 \, ft] on August 4 about stem:[10 \, miles] upwind of the launch site, under similar wind conditions.

== Results

*Figure 2* shows the time changes in the particle volume concentration measured during the flight; superimposed on it is the sulfur content of the aerosol. The volume concentrations were calculated from the particle size distribution and the sulfur was obtained from the analysis of the hi-volume filter by x-ray fluorescence. The volume concentration is averaged over 15 min of sampling time. The figure shows three distinct features of the aerosol mass concentration profile. The first 60 min the sulfur and particle volume concentrations decreased with time reflecting the domination of plume dilution by diffusion over particle growth. During the second 60 min, plume diffusion was less significant and the particle volume concentrations decreased. At the end of this period a new material was entrained onto the air parcel resulting in a decreased concentration. At this point the pilot reported smoke from below having reached the sampling level. Apparently this new material has a lower mass concentration but the total number of particles is higher. The latter conclusion is based on examination of the variation of the total particle number concentration with time (*Figure 3*). As expected the first 2 hr were characterized by a continuous decrease in the particle count as a result of particle growth and plume diffusion. Beyond this point the count started to increase. Although the number concentration was calculated from the measured particle size distribution, a similar profile was also observed from the {gen-ait} (*Figure 4*).

*Figure 4* shows the variation of other parameters measured during the flight. The relative humidity value ranged 50-60% and the temperature fluctuated around stem:[20°C]. The change in altitude with time is the sampling altitude but it was very close to the tetroon level. The ozone level slightly increased with time to the sampling altitude but it was very close to the tetroon level. The ozone level slightly increased with time. On the other hand, the NO/NO~2~ ratio decreased and showed no correlation with the ozone. This behavior is typical for the flights we made. The NO and NO~2~ levels remained always below about stem:[20 \, ppb] except when a plume was encountered along the tetroon trajectory. In this case a drastic drop in the O~3~ level was observed associated with an increased NO/NO~2~ ratio.

*Figure 5* shows the changes in the particle number distribution, and the same data is plotted in *Figure 6* in terms of volume distribution. Particles of sizes below about stem:[0.06 \, \mu m] were growing to sizes up to stem:[0.9  \, \mu m]. Since the total number of particles was decreasing while the total volume was increasing, the particles were growing by coagulation and chemical condensation. No evidence of homogeneous nucleation of particles can be seen from this data. Similar behavior was also observed Husar and Whitbyfootnote:3[R. B. Husar and K. T. Whitby, "Growth Mechanisms and Size Spectra of Photochemical Aerosol," Environmental Science and Technology, Vol. 7, 241-247, 1973.] when a large balloon was inflated with {la} ambient air and exposed to solar radiation.

It is useful to compare this size distribution measurement with those measured a year earlier on August 21, 1974. For this experiment, the tetroon was released to an altitude of stem:[3000 \, ft \, MSL], from the {cair}, about noon under clear sky with an average wind speed of about stem:[8 \, knots]. *Figure 7* shows the size distributions measured. The particle growth is similar. The two sets of particle size distributions showed the bimodal nature of the distribution. The first mode roughly lies between stem:[0.06 - 0.9 \mu m], the so-called accumulation modefootnote:4[K. T. Whitby, "On the Multimodel Nature of Atmospheric Aerosol Size Distributions," presented at the VIII International Conference on Nucleation, Leningrad, USSR, September 28, 1973.]. Particles in this range grow by coagulation and/or condensation. The second mode is above about stem:[1 \, \mu m]. Particles of such sizes showed no detectable growth, and as can be seen from *Figure 7*, their number decreased with time as a result of plume diffusion. Plume diffusion does seem to dominate the growth of smaller particles as the case of August 6. 

The experiment described above is part of the aerosol and trace gases transformation program aimed at understanding pollutant transformation through field experiment and modeling, with a strong interaction between the experiment and the models. The models are described elsewhere by Halesfootnote:5[J. M. Hales, "Proteus: A User Oriented Computer Code for Solutions of the Continuity Equation for Trace Substances in the Atmosphere," Pacific Northwest Laboratory Annual Report for 1974 to the USAEC Division of Biomedical and Environmental Research, Part 3, Atmospheric Sciences, BNWL-1950, PT 3, Battelle, Pacific Northwest Laboratories, Richland, WA, 1975.] and Drakefootnote:6[R. L. Drake, “Aerosol Balance Equation: Numerical Modeling,” this volume.].

== Acknowledgements

The author wishes to acknowledge the contributions of {KMBu}, {RNL}, {NSL}, and {JWT} who participated in the field operation and data reduction; to {DRD} who developed a computer program for data analysis; to {JMH}, {CEE}, and {RLD} for their valuable discussion and remarks throughout the year; and to {FOG} and {WRG}, the pilots.

NOTE: This Abstraction has been accepted for presentation in the {ISAP-12}, 5-7 May 1976, Paris, France.