[id="con_particle_deposition_penetration_through_canopies_{con-particle-depo-penetration}"]
include::../attributes.adoc[]

== Introduction

Particle deposition velocities are a function of many variables including surface, particle, and meteorological parameters. Predicted deposition velocities can vary from about _10^-4^ to 10^2^ cm/sec_ as a functionfootnote:1[G. A. Sehmel, “Comparison of Deposition Velocities Predicted from Dimensionless Analysis Correlections,” see this report.],footnote:3[G. A. Sehmel and W. H. Hodgson, “Predicted Dry Deposition Velocities,” Proceedings of the Atmosphere-Surface Exchange of Particulate and Gaseous Pollutants - 1974 Symposium, Richland, Washington, Sept. 4 - 6, 1974, ERDA Symposium Series CONF-740921 in press, November 1975.] of particle diameter, particle density, friction velocity, and aerodynamic surface roughness. However, prediction procedures can not yet describe the effects of foliage density on deposition velocities, nor particle penetration through the foliage to the underlying surface. Since initial results indicated significant particle penetration through the top layer of a crushed gravel deposition surface, particle penetration could also be significant for vegetation canopies. Consequently, penetration results and foliar deposition velocities are needed to improve deposition velocity models. Here we report large particle penetration results to a crushed gravel surface and also penetration and deposition velocities for an artificial tree foliage fetch 9 cm high.

== Experimental

Deposition velocities and particle penetration were measured in a _61 cm by 61 cm_ cross section wind tunnel, using monodispersed uranine particles. Experimental techniques have been describedfootnote:4[G. A. Sehmel and W. H. Hodgson, “Penetration of Depositing Particles through Crushed Gravel,” Pacific Northwest Laboratory Annual Report for 1974 to the USAEC Division of Biomedical and Environmental Research, Part 3, Atmospheric Sciences, BNWL-1950, Battelle-Northwest, Richland, Washington, pp. 181-183, 1975.]. In brief, air concentration is measured by isokinetic sampling and deposition in water. The mass of uranine is determined florimetrically from the wash solution.

The crushed gravel deposition surface covered the entire _7.3 m_ by _61 cm_ wind tunnel floor to a depth of approximately _5 cm_. Average gravel sieve diameters were between _3.8_ and _5.1 cm_. Deposition was measured on test sections _22 cm_ wide by _30 cm_ long, located between _4.7_ and _6.3 m_ along the wind tunnel midplane.

The artificial tree foliage section was mounted on a _23 cm_ by _30 cm_ long plastic plate laid on top of the gravel surface at the _6.9 m_ length of the wind tunnel. Trees were mounted in the plate in a rectangular array with eight downwind rows of trees. Tree spacing was 3.8 cm. The polyethylene trees were _7 and 9 cm_ high with a maximum crown width of _4 to 6 cm_. Each crown had eight branches located around the central trunk, and the tree trunk extended _~2 cm_ below the crown. Particles depositing on the trees and plate were washed off and analyzed separately.

== Results

Nonuniform particle deposition in the tree fetch indicated edge effects. Depending upon particle diameter and wind speed, the front has less deposition than downwind rows. These edge effects extended for three to five rows. Since particle penetration to the entire plate was significant, deposition velocities for each deposition velocity for all trees and the plate are shown in *Figure 1*. The two wind speeds were measured upwind and at _6 cm_ above the gravel surface. This _6 cm_ height is approximately the height of the tree crown mid-plane.

Deposition velocity curves show different patterns than those for simpler surfacesfootnote:1[],footnote:2[G. A. Sehmel and W. H. Hodgson, “Particle Dry Deposition Velocities,” Pacific Northwest Laboratory Annual Report for 1974 to the USAEC Division of Biomedical and Environmental Research, Part 3, Atmospheric Sciences, BNWL-1950 PT 3, Battelle-Northwest, Richland, Washington, pp. 175-180, 1975.],footnote:3[]. At a wind speed of _2 m / sec_, a minimum deposition velocity occurs at about _1_ to _2 μm_ for the trees. In contrast, simpler surfaces have minima in the particle diameter range from _0.1_ to _1 μm_. For a _13 m / sec_ wind speed, deposition velocities are nearly constant for all particle diameters studied. Again, in contrast, deposition velocities for _2 μm_ compared to larger particles would be significantly less for simpler surfaces.

Particle penetration to the plastic mounting base for the trees shown in *Figure 2*. Penetration is the deposition to the plate as a percent of the deposition to the plate and trees. Penetration was significant with a maximum value of 83%. Penetration is a function of both wind speed and particle diameter. A cross-over diameter is about 4 μm. For particles smaller in diameter, penetration is greatest at the low wind speed. For larger particles, penetration is greatest at the high wind speed.

Penetration through crushed gravel is shown in *Figure 3*. In this case, the two wind speeds were measured _3 cm_ above the gravel surface. The particle diameter range is larger in this figure. Penetration is greater at the slower diameters from _3 x 10^-2^ μm_ to the _9 μm_ cross over diameter.

The penetration curves for crushed gravel and trees are similar. Penetration is larger for the slow wind speeds for particle diameters below the cross-over points. Penetration is larger for the slow wind speeds for particle diameters below the cross-over point. However, the particle diameter at the cross-over point is a factor of two (_4_ versus _9 μm_) less for trees than for crushed gravel. Apparently the nonrigid tree motion and open tree structure tend to enhance resuspension at the smaller _4 μm_ particle diameter as compared to the rigid, more dense gravel structure. For particles larger than the cross-over point, penetration was always greater at the higher wind speed.

An explanation was sought for these penetration similarities. One possibility is that above the crossover point deposition and resuspension occurred simultaneously at the higher wind speed. If particles resuspended from the upper surfaces of the gravel and trees while the flux of penetrating particles remained constant, the observed penetration would increase since fewer particles remained deposited on the upper surfaces. For particles smaller than the cross-over diameter, a satisfactory suggestion is yet needed to explain higher penetration at lower wind speeds. Possibly for these particle relaxation times the air turbulence scale and intensity or relative wind profiles through the canopies are sufficiently different for the two wind speeds.

== Conclusions

Predictive deposition velocity models must eventually consider both depositions within vegetative canopies as well as deposition penetration to the underlying surface. However, this penetration database is very limited and consequently penetration cannot yet be generalized in predictive models. Deposition velocities to vegetation (_9 cm_ trees) do show edge effects at the entrance to the “grove” of vegetation. Similar edge effects may be very important within forests since most forests contain many clearings from small to large size. Indications are that resuspension could probably occur simultaneously with deposition on the upper surfaces of vegetation.