[id="con_design_chemistry_measurement_analysis_{con-design-chemistry-analysis}"]
include::../attributes.adoc[]
:stem: latexmath

== Introduction

The use of fossil fuels in energy production has increased steadily; the electrical output has more than doubled in the past 10 years. This increase, and continued increasing use of fossil fuels - particularly coal in the northeastern {US}, could significantly affect the environment. Recent research has indicated that a trend toward more acid precipitation in the northeast has paralleled the increased fossil fuel use; in addition, it seems that the original pollutant of most concern, SO~2~, has been supplanted by its oxidation product sulfate. The use of tall stacks to disperse SO~2~ and other gaseous pollutants has apparently allowed for the existence of sulfate and other products of reactions in the atmosphere at great distances from the source.

Careful and consistent monitoring of air and precipitation quality is of great importance in assessing the impact of these trends to the affected region. Unfortunately, collection of precipitation for chemical analysis in the northeast has been rather nonuniform in terms of chronological and geographical coverage, sample collection and analysis practices. *Figure 1* shows the sites of present collections in the eastern {US}.

A research project, Precipitation Scavenging of Fossil-Fuel Pollutants on a Multi-State Scale, has been initiated to fulfill the overall objective: the design and institution of a regional precipitation collection network which will avoid past difficulties and provide a basis for a high-quality system of monitoring and data collection for the future. The design of this system places particular emphasis on 1) developing a reliable wet deposition collector; 2) careful siting of collection stations to avoid local source influences and provide adequate coverage of the region; and 3) instituting chemical analysis procedures that provide rapid analysis of all relevant pollutant species and fast dissemination of results to interested scientists and environmental policy makers.

The first year’s effort has concentrated on the development of sampler hardware (described in another report in this volume) and institution of several initial sites in the northeastern United States. The latter effort is being coordinated by personnel of the {ARL} of NOAA; *Figure 1* shows the initial sites proposed for deployment by mid-1976. The precipitation chemistry of each locale will be examined prior to the location of the exact site, which will then be outfitted with the Battelle sampler. Progress has been made toward location sites as follows: {ith}, {NY} (in cooperation with {corn}); {wf}, {NY} ({SU} of {NY}; and State College, {PA} ({PA} {SU}).

The chemical analysis will be performed primarily at the Richland laboratories of Battelle. Wet chemical methods will be used for analysis of these species: SO2 (dissolved), SO4̳, NO2̅, NO3̅, NH4^+^, H^+^ (pH measurement and titration methods), PO~4~^3-^, and conductivity. The eventual list of species to be considered routinely will also include Cl, Na, K, Mg, Ca and carbonates. Of primary importance in this area is the institution of careful and well-defined methods for sample analysis. Full documentation will be provided so that the quality of data will be subject to review at all times. The chemical analysis will be completed as soon as possible after sample collection, and a report of results will be disseminated regularly and promptly through the use of a special data output format.

The northeastern United States network will be expanded in future years in cooperation with other laboratories engaged in precipitation chemistry research. In particular, close coordination with the {ilwater}, whose pork plans include a midwestern network, is a goal of the present project. The expanded operating network and developed chemical analysis and quality control methods should form an important component of the {multistate}.