[id="con_a_regional_scale_model_elevated_source_{con-regional-scale-elevated-source}"]
include::../attributes.adoc[]
:stem: latexmath

== Introduction

During the past year the most urgent regional pollution problem associated with power generation has been generation of sulfur compounds by fossil fuel combustion. Both the government and private industry are sponsoring programs to investigate the environmental impact of the SO~2~-sulfate cycle as the demand for energy requires continued and increased use of sulfur-bearing fuels.

The seriousness and complexity of this problem have been pointed out in a lengthy report prepared for the {commit} of the {US} Senatefootnote:1[Commission on Natural Resources, "Air Quality and Stationary Source Emission Control," prepared for the Committee on Public Works, U.S. Senate, Senate Resolution 135, Supt. of Documents, U.S. Printing Office, Series 94-4, 1975.]. This report indicates that oxidation products of SO~2~, including sulfuric acid and suspended particulate sulfates are more toxic than the parent compound. This problem takes on multistate proportion, introducing formidable challenges to the development of a realistic assessment model.

The initial considerations and beginnings of this modeling effort have been previously describedfootnote:2[L. L. Wendell and D. C. Powell, "Regional Transport Dispersion and Removal of Atmospheric Pollutants," Pacific Northwest Laboratories Annual Report for 1974 to the USAEC Division of Biomedical Research, Part 3, Atmospheric Sciences, BNWL-1950, PT 3, Battelle, Pacific Northwest Laboratories, Richland, WA, February 1975.]. A model has now been developed and subjected to initial testing. The model is designed to use time- and space-varying gridded wind and precipitation data, along with user-specified source locations and source strengths to compute average air concentrations and deposited amounts of SO~2~ and sulfate. The model simulates transport and dispersion, chemical transformation, and wet and dry removal. In this first version of the model the simulations of the transformation and removal processes are of a simple linear nature. They do, however, allow some investigation of the sensitivity of the overall process to its interacting parts. Options have been left open to allow more sophisticated treatment when the appropriate knowledge becomes available from experimental programs. The description of the model in this report will be brief; more detailed documentation for formal presentation is in progress.

== Transport and Dispersion

The transport of material in this model is purely kinematic and is accomplished using similar techniques as developed for mesoscale purposes. The model is designed to accept a time series of gridded winds, assumed to be representative of the layer carrying the contaminant. The grided wind fields for this work are currently generated from 12-hourly radiosonde data. The model approximates a continuous plume centerline by a series of  particulates released from selected source locations at 1-hr intervals, into wind fields obtained by hourly interpolation between the 12-hourly observations. An example of the result of this procedure is displayed graphically in *Figure 1*. The positions of the particle are computed on an hourly basis.

The plumes depicted in Figure 1 are analogous to a satellite picture 12 and 24 hr after release. Despite the fact that this type of representation only approximates what is happening in the atmosphere, it provides some interesting depictions of plume stretching and overlapping in a time- and space-varying flow on this scale.

Dispersion of the mass of material associated with each particle is allowed to develop in a Gaussian fashion. The variable stem:[\sigma_{z}] is approximated as described previouslyfootnote:3[L. L. Wendell, "Mesoscale Wind Fields and Transport Estimates Determined from a Network of Wind Towers," Monthly Weather Review, Vol. 100, No. 7, July 1972, pp. 565-578.]. The variable stem:[\sigma_{y}] is approximated with the form

.Equation 1
[latexmath]
++++
\sigma_{y} \; = \; ax^{b}
++++

where stem:[x] is distance traveled by the particle of concern and the values of stem:[a] and stem:[b] are selected according to the stability class to reproduce the Pasquill-Gifford curvesfootnote:4[D. H. Slade, Ed., Meteorology and Atomic Energy, U. S. Atomic Energy Commission, Division of Technical Information, available as TID-24190 from the National Technical Information Service, U.S. Department of Commerce, Springfield, VA, 22151, p. 404, 1968.]. The plume widths shown in *Figure 1* are determined by assuming the plume edges to be stem:[2 \sigma_{y}] from the centerlines, making a total width of stem:[4 \sigma_{y}].

The average surface air concentrations and the deposition quantities are calculated by sampling the approximated plumes over a network of grid squares, approximately stem:[34 \, x \, 34 \, km]. The model has been constructed with the option of neglecting horizontal diffusion about the plume centerline. This is an assumption made by others in long-term assessment models on a similar spatial scalefootnote:5[Bert Bolin and Christer Persson, “Regional Dispersion and Deposition of Atmospheric Pollutants with Particular Applications to Sulfur Pollution Over Western Europe,” Tellus CVII, 3, pp. 281-310, 1975.]. Preliminary tests comparing runs with and without horizontal plume diffusion indicate that the extra expense (factor of stem:[4]) is probably not justified for long-term assessments.

==Transformation

The chemical processes involved in the transformation of SO~2~ to sulfates, including sulfuric acid, in the atmosphere are complex and the subject of considerable investigationfootnote:6[Commission on Natural Resources, “Air Quality and Stationary Source Emission Control,” prepared for the Committee on Public Works, U.S. Senate, Senate Resolution 135, Supt. of Documents, U.S. Printing Office, Series 94-4, 1975.]. However, for the current version of the model of the oxidation reaction has been assumed to be linear with a user-specified fraction per hr*. This rate could be made to vary with relative humidity or the presence of other chemical species, but the present assumption is probably in line with the assumptions regarding diffusion.

== Dry Deposition

The dry removal processes involve 1) the absorption of gaseous SO~2~ by the soil or vegetation and 2) deposition of particles containing sulfates. These processes have also been assumed linear with user-specified deposition velocities.† No accounting is made at present for spatial variation of roughness or vegetation type but the computer code can easily be adapted to account for this when experimental programs provide adequate data to do so. The current version of the model uses source depletion instead of a surface depletion in the dry deposition calculations. For a deposition velocity stem:[1 \, cm/sec] and a transport velocity of about stem:[10 \, m/s] the discrepancy would be on the order of 30%footnote:7[T. W. Horst, "A Surface Depletion Model for Deposition from a Gaussian Plume," BNWL-SA-5096, presented at the Atmosphere-Surface Exchange of Particulate and Gaseous Pollutants Symposium - 1974, Richland, WA, AEC Symposium Series, CONF-740921, September 4-6, 1974.]. The error would increase for lower transport velocities. Methods for correcting this problem are being examined and evaluated; an appropriate method will be incorporated into the model to more realistically approximate the surface depletion.

The model in its present form will accept either gridded hourly precipitation rates or average precipitation rates. An example of the effects of the real-time precipitation data is shown in *Figure 2*. For the purposes of this graphical display any portion of the plume encountering a precipitation rate greater than stem:[0.01 \, in./hr^{-1}] was immediately dropped. Precipitation scavenging is incorporated into the assessment model through the application of a washout coefficient which is directly proportional to the precipitation ratefootnote:8[W. G. N. Slinn, "Some Approximations for the Wet and Dry Removal of Particles and Gases from the Atmosphere," BNWL-SA-5489, submitted for publication in the Journal of Air, Water, and Soil Pollution.]. In-cloud or below-cloud scavenging are not included in the present version of the model, however methods are under investigation.

== Illustration and Combined Transformation and Removal Effects

The simultaneous occurrence of transformation of SO~2~ and sulfate at different rates for each can be difficult to visualize. The effects of these combined processes as they are approximated in the model for a single plume element are shown in *Figure 3*. The main feature which is apparent in the diagram is the limiting effect the removal processes have on the SO~2~ available for conversion to the sulfate which, because of its postulated lower removal rates, can be carried long distances from the source. This is especially apparent in comparing *Figure 3b* and *3c*. The relative magnitudes of the fractions of the original SO~2~ in the air as sulfate and deposited at the surface, are dramatically reversed as wet removal is added as a continuous process. It is interesting to note that in the wet removal by an intermittent process the effect on the amount of SO~2~ available for conversion to sulfate would depend strongly on the travel time available before precipitation is encountered. This effect is currently under investigation.§

== Discussion

The present model contains the essential elements, in varying degrees of approximation, to begin validation and assessment exercises. Our approach in this modeling effort is to maintain a balance between development and application. Our objective is to produce a model which will serve as a vehicle to be improved upon. This approach allows the validation efforts, the assessment exercises and comparisons with other models to suggest the priority of the required improvements. These efforts, coordinated with the efforts of other FRDA-supported laboratories should provide an essential tool to aid in making the decision required to establish fossil fuel energy policy.

NOTE: _*_ See accompanying article, "Chemical Deposition and Transformation Parameterizations for Regional Models," by {RLD}, this volume.

NOTE: _†_ See accompanying article, "Preparation of Hourly Maps of Gridded Precipitation Scavenging Calculations," {LLW} and {CEH}, this report.

NOTE: _§_ See accompanying article, "An Examination of the Effects of Real Time Versus Time Averaged Precipitation Data on SO2 and SO4 Removal in the Regional Assessment Model," {LLW} and {DCP}, this report.