[id="con_solvent_refined_coal_organic_constituents_present_{con-solvent-refined-coal-organic-constituents}"]

== Introduction

What are the potential emissions of any new process developed to obtain energy from fossil fuels? This question is particularly important for processes involving coal or any method to transform coal into a cleaner burning fuel. Since any constituents in the process streams are potential pollutants, knowing their identity and relative concentration before commercializing the process, provides a data base for proper emission control. During this last year we have sampled a pilot plant producing solvent-refined coal. Of the numerous organic constituents in the process streams we have identified about 50 major components.

== Facility Sampling

The 50/ton daily pilot plant located near Fort Lewis, Washington, and operated under ERDA contract by the Pittsburg and Midway Coal Mining Company produces solvent-refined coal which meets design specifications for reduced emissions during firing. In the process, crushed coal is mixed with a recyclable coal-derived solvent and heated to about 825°F in presence of hydrogen at 1000 psi or greater. The coal swells and then dissolves. The solution is filtered to remove the inorganic residue and evaporated. The product which solidifies is a refined coal with less than 1/2% of either sulphur or residual ash.

The objective of our study is to collect samples at various processing points and determine the organic components which may be viewed as potential pollutants. The following samples have been collected: process solvent, mineral residue, process effluent water, process naphtha and the fuel product. The samples or extracts of the samples were characterized using gas chromatography with a flame ionization detector or a combination of a gas chromatography-mass spectrometry. A typical chromatogram of the process naphtha is shown in *Figure 1*; it exhibits the complex mixtures of organic compounds present in the samples. To simplify the complexity of the mixture, the components in each bulk sample were separated into acidic, neutral, and basic organic components. It was found that the neutral fraction (consisting mainly of aromatic hydrocarbons) predominates; the acidic fraction (consisting of phenolic compounds) makes up less than 20% of total compounds; the basic fractions are minor components of less than 5%.

== Analysis

About 50 compounds have been identified in the samples collected thus far. Although the positional assignments on some of the methyl groups are tentative, the compounds listed in *Figure 1* are the predominant neutral and acidic species common to all the samples. Quinolines are the predominant basic compounds; due to their low concentrations, they cannot be seen in the chromatogram shown. Many of the compounds detected are toxic and only one (dibenzothiophene) has been reported as carcinogenic. Although presumably present, benzo(a)-pyrene, it appears to be a very minor component.