[id="con_precipitation_scavenging_1975_olympic_{con-olympic-peninsula-storm}"]
include::../attributes.adoc[]
:stem: latexmath

== Introduction

The experimental design described in an accompanying articlefootnote:1[C. E. Hane and J. A. Young, "Design for In-Cloud Scavenging Experiments on the Olympic Peninsula," (this report).] was taken in March 1975 to the {nw} {OP} with the intent of performing as many of the experiments as possible within the time allowed. Dual Doppler radars from the {WPL} in {boul}, {CO}, were deployed at {QAF} and at {MAF} Base near {NB}, {WA}footnote:1[], *Figure 1*. A newly-acquired DC-3 aircraft equipped with instruments for monitoring cloud physicsfootnote:2[J. M. Hales, "Development of a DC-3 for Atmospheric Pollution Research," this volume.] properties and for releasing tracers was stationed in Everett, {WA}. The aircraft stood by for call-up by the experiment leaders, who monitored the weather conditions closely with the surveillance radar Makah, special radiosonde releases, and helicopter transmissions from the {NWS} Office in {sea}.

== Sampling and Analysis

On March 14, 1975, a cold front approached the experimental area from the {nw}. The satellite photographs indicated an extensive cloud shield accompanying the front, and radar indicated precipitation moving into the area during the early morning hours. The aircraft was called to the area and tantalum was released (est. stem:[230 g]) within a small ell at an altitude of stem:[500 ft] (stem:[3°C]). The {sw} of the {QAF} and was moving toward the northeast at stem:[5 nm] {sw} of the {WAF} and was moving toward the {ne} at the time of release (1024 PST). The release, made over a 2-min period, was done mechanically (without burning) due to electrical failure aboard the aircraft which prevented conventional burning in the acetone generators. The Makah RH radar and the Doppler radars indicated cloud tops to be at only stem:[7000 ft]. during this time, and precipitation elements did not attain sufficient size to be observed by {doppd} techniques because of the shallow wind layer. Using the winds obtained by special radiosonde releases during the experiment at {QAF}, along with assumptions regarding incorporation of tracer into falling rain, an estimate was made of the deposition pattern, and a number of the collected samples were analyzed for the tracer.

No tracer was detected above background in the analyzed samples. The reason for the lack of scavenging in this case is very likely the lack of storm intensity. A possible conclusion, therefore, is that scavenging by frontal storms less than stem:[5000 ft] thick is inefficient, compared to scavenging by storms stem:[~10000 ft] or more deep which are known to deposit more on the ground a significant fraction of released tracerfootnote:3[C. E. Hane and J. A. Young, "Design for In-Cloud Scavenging Experiments on the Olympic Peninsula," (this report).]. This conclusion, however, needs substantiation through additional field experiments with weaker storms, or through calculations from a microphysical model which has been verified by field experiments in stronger storms. Since a substantial fraction of the storms approaching the northwest U.S. coast occurs with {nw} flow aloft and low moisture supply (as was the case here) perhaps it is important to attempt to understand scavenging by some means in these storms as well as in the more intense storms occurring under more {sw}ly flow aloft.

On March 15, 1975, *Experiment III* footnote:1[] was run with some last-minute modifications. The aircraft, equipped with instruments for vertical soundings and a chaff cutter, was not available due to mechanical difficulty, so that the experiment was performed using chaff rockets and radiosondes only. Winds during the experiment were southerly to the southwesterly at 20-30 m/sec with only slow veering between the surface and stem:[~7000 ft]. Rockets were launched near the 4 locations noted in *Figure 4a*, including 6 rockets releasing a total of 10 chaff packets at various altitudes between stem:[2000] and stem:[5000 ft]. The rocket firings at locations closer to the ridge were delayed so that chaff from all sites might cross the ridge at more nearly the same time. Radiosondes were released from the {QAF} a few minutes before the first rocket firing and a few minutes after the last firing (time interval between radiosondes was stem:[75 min]). The {dopp} at {QAF} was able to see only one chaff packet and the Doppler radar at Makah saw none of the chaff packets. The reason for this surprising result is not clear, though it is possible that the terrain between the radars and packets prohibited the return from some of the lower altitude packets. Also, the weather on this day was rather showery, this may have obscured some of the packets, which yield a weaker return than chaff released by other means. During a test field on another day, chaff was released by means of a chaff cutter on board the DC-3 aircraft. That strip of chaff provided an excellent return to the {doppr} which could be tracked for a considerable length of time. Orographic airflow experiments of this type, therefore, might be performed more satisfactorily using aircraft chaff releases, instead of rocket releases, even though this would sacrifice the capability for near-simultaneous releases at different locations.

Some of the best data obtained by the {dopp-2} resulted from some moderately intense convective storms which occurred during the morning and afternoon of March 16, 1975. This convection resulted from the destabilizing influences of very cold air aloft in an upper level through which moved from west to east over the area. The activity could be seen clearly, far to the west over the {PacO}, on satellite photos from the previous day, and was well behind a cold front which had passed through the area on the previous morning. It was definitely not a locally produced phenomenon. During the day on the 16th, the local weather fluctuated remarkably with sunshine one hour and heavy precipitation the next, including several instances of graupel covering the ground.

Data from this day are being analyzed at the present time by the {MRU}, {WPL} of the {NOAA} (NOAA) in {boul}, {CO}. A sample of this day’s output is shown in *Figure 1*. The arrows represent velocity perturbations within the rain area of one of these convective storms. The velocities result rom computing the mean total velocity at all the points and then subtracting the mean of the field from the total velocity at each point. These velocities are not quite the same as the relative velocities since the relative velocities are obtained by subtracting the motion of the system from the total velocity at each point. The motion of the system may differ from the mean motion of the air within the system.

== Conclusions

Several comments concerning precipitation scavenging may be made with reference to the data in *Figure 1*. Relative inflow occurs along some of the periphery of this storm, and relative outflow occurs in other locations. Therefore a material from an outside source which might be scavenged may or may not be incorporated into the rain area, depending on where it approaches the storm periphery. In this case, the velocities are at low levels (stem:[1-1.5 \, km \, msl]) where the storm motion is probably faster than the component of air motion in the direction in which the storm is moving. In other words the storm is overtaking the air at this altitude. Outside material would therefore be located on the east-{ne} edge (the direction toward which the storm is moving) and would be incorporated into the rain area readily because of the confluent nature of the flow. Whether the material would be scavenged or not depends upon several more factors: 1) Will it be incorporated directly into the rain? Or 2) Are the motions in the rain area where it enters the storm upward (in which case it might be scavenged in the condensation process)?

These questions can be better answered when more data are available at other levels in the storm. In conjunction with future field experiments it may be possible with such data to compute the horizontal convergence at different levels, assume some vertical velocity at different points just below the lowest horizontal plane, and integrate the mass continuity equation to obtain vertical air motions within the rain area. Given the {3D} velocity field and the spatial distribution of liquid water, one might calculate trajectories of materials injected into the storm, assume various possibilities for scavenging mechanisms, and compute the deposition pattern on the ground. To complete the picture, scavenged amounts obtained from field experiments should be compared with the calculated result. The calculation might be done first, however, to estimate where the material might be deposited in relation to where it is released. The field experiments in March 1975 were not designed for this type of storm which very likely produces only a small fraction of the annual rainfall on the {OP}. Whether it accomplishes only a small fraction of the total scavenging is yet another question.

One final observation relating to *Figure 1* is the possible effect of orographic influences in determining the velocity pattern shown. There appears to be some correlation between the high velocity vector through the center of the pattern pointing toward the southwest and the higher terrain features (also coarsely depicted in the figure). When radar data at other times and locations become available, the relation between terrain features and possible stronger areas of upward motion will be carefully studied. We hope that a better knowledge of this relation will aid in interpreting some of the deposition patterns of tracer released in past frontal storm field experiments in exactly this same section of the {OP}.

== Acknowledgements

The March 1975 field operation was a largely developmental field series characterized by innovations in observing systems. Storms highly suitable for experiment were lacking and some unavoidable instrument failures did occur in spite of the dedicated efforts of the field personnel who, besides the two authors, included: {WED}, {DRD}, {DRE}, {RFE}, {OPG}, {FOG}, {DWG}, {JMH}, {MCM}, {BCS}, {JMTa}, {CWT}, and {JMT}. In addition, others too numerous to mention were closely involved in preparations for going into the field. We are also grateful for the kind cooperation of personnel of the {NWS} at {quil}, or the 758th U. S. {AF} Radar Squadron at the Makah Base, and of the  {NWS} in {sea}. In addition, special thanks to {ASF}, {RGSt}, and {WCC} of the {WPL} (NOAA-{boul}) for their efforts in sitting and manning the {doppr}.

NOTE: The *Figure 4a* and *Illustration III* figures referenced in the report are not included with the report.