=== Introduction

Several results are presented from comparative analysis of atmospheric pollutants measured in 1975 at Quillayute Air Reference Station located in northwestern Washington. A description of the site and sampling techniques used were presented.footnote:1[J. D. Ludwick, C. W. Thomas, L. L. Wendell and T. D. Fox, "Quillayute Air Reference Station," Pacific Northwest Laboratory Annual Report for 1974 to the USAEC Division of Biomedical and Environmental Research, Part 3, Atmospheric Sciences, BNWL-1950, PT 3, Battelle, Pacific Northwest Laboratories, Richland, WA, February 1975.] in the 1974 Annual Report. Included here are graphic monthly computer readouts of physical and chemical information accumulated since then.

=== Ozone

Meaningful positive or negative correlations between many atmospheric materials are often masked by physical and chemical processes affecting the species of concern. For example, the influence of pollutant materials on the ozone concentration at low level is illustrated in *Figure 1*. This is a typical situation at Quillayute; high particulate concentrations occur at some 20% of the time due to the presence of moderate atmospheric stability. The resultant stagnation drastically increases the concentration of particulates near ground level. Gaseous pollutants are also trapped under the inversion layer. The data indicate that when this occurs, the ozone is rapidly depleted through reaction with these pollutants. The lack of a significant low level ozone source may also be postulated from these results.

Significant depletion of ozone was observed within 5-20 min of sunrise, indicating a high reaction rate, probably of first order kinetics, not involving a third body. The rapid ozone depletion under stable conditions also suggests that ground interaction is not the prime factor since the sampling port is located 33 m high.

The diurnal effect promoting anti-correlation in the ozone particulate was not the only data observed. Specific cases of such particulate scavenging are difficult to identify with complete confidence; however, the data most certainly suggest that this effect is prevalent. Often, the level of particulates in incoming fresh air is low and the effect of precipitation scavenging is difficult to identify.

In summary, the major chemical and physical factors, the summary, the major chemical and physical factors affecting the ozone and particulates tend to decorrelate their relationships. It is then particularly significant that such correlations exist in Quillayute data. 

=== Radionuclide correlations

This inference was pointed out in data presented previously.footnote:1[] To better illustrate this fact, the ozone data were replotted in an identical form to the radionuclide information. The daily maximum observed ozone concentrations were used as most representative of the tropospheric values in the vicinity of our monitoring station. *Figures 7 and 8* illustrate the positive correlation between ozone, beryllium, and fallout radionuclides. During a good deal of September, the meteorological situation was quite well defined. An upper level high prevailed over the region. This was conducive to the transport of high altitude materials downward. Late night and early morning inversions at Quillayute developed under this high pressure, resulting in depletion of the ozone. However, as daily thermal activity penetrated the stable layer by early afternoon, very large increases in the ozone were observed. Accompanying this ozone was a large amount of particulate ^7^Be; ^7^Be is an upper tropospheric and stratospheric product of cosmogenic origin. 

The annual fluctuations of materials whose major source region is suspected to be stratospheric is shown in *Figure 9*. Springtime increases of these materials in the troposphere in the northern latitudes are to be expected from previous work on fallout patterns.footnote:2[C. W. Thomas, et. al., "The Measurement and Behavior of Airborne Radionuclides Since 1962," Advances in Chemistry Series, Radionuclides in the Environment, 93:158 (1973).] High values of ozone and Be during the fall are rather unique, perhaps due to the persistent high pressure area previously mentioned.

Many recent studies have indicated that rural ozone concentrations are as high or higher than urban concentrations. Frequently they exceed the national air quality standards of 80 ppb.footnote:3[W. N. Stasiuk, Jr. and P. E. Coffey, "Rural and Urban Ozone Relationships in New York State," Journal of the Air Pollution Control Association, 24, 564 (1974).],footnote:4[S. M. Bruntz, et. al., "Ozone Concentrations in New Jersey and New York: Statistical Association with Related Variables," Science, 186: 257 (1974).],footnote:5[A. Miller, "Rural and Urban Ozone Relationships," Journal of the Air Pollution Control Association, 24:819 (1974).] Daily maximum ozone statistics from our Quillayute, Washington air monitoring stationfootnote:1[] are compared with similar data from sites in New York and New Jersey in *Table 1*.footnote:4[]

Although the median Quillayute ozone concentration is comparable to the lower median New York concentrations, the upper quartile and upper decile Quillayute values are far below those of the eastern sites. Furthermore, although urban and rural eastern sites occasionally exceeded the air quality standard of 80 ppb, the maximum Quillayute ozone concentration reached between April and November 1974 was 60 ppb.

=== Conclusions

The day-to-day changes in daily maximum ozone concentrations at Quillayute have been related to the transport of stratospheric materials.footnote:1[] Such fluctuations apparently cannot account for occasionally much higher values reported in more polluted regions by Bruntz and others.footnote:4[] Thus, the Quillayute data indicate tha a stratospheric source ozone is probably responsible for only a portion of surface ozone concentrations which exceed the National Ambient Air Quality Standard of 80 ppb. The additional ozone may well be derived from low-level pollution sources as many investigators have long suggested.