[id="con_use_of_elemental_concentration_rations_to_distinguish_between_the_plumes_northeast_{con-use-elemental-concentration-rations-plumes-northeast}"]
include::../attributes.adoc[]

== Introduction

Measurements of the atmospheric concentrations of various trace elements in and downwind of major U.S. cities by several investigatorsfootnote:1[S. S. Brar, D. M. Nelson, J. R. Kline, D. F. Gustafson, E. L. Kanabrock, C. M. Moore, and D. M. Hattor, "Instrumental Analysis for Trace Elements Present in Chicago Area Surface Air," Journal of Geophysical Research 75, 1970.]footnote:2[R. F. Tuttle, J. R. Vogt, and T. F. Parkinson, "Neutron Activation Analysis of Trace Elements in Airborne Particulates," IAEA Symposium on the Use of Nuclear Techniques in the Measurement and Control of Environmental Pollution, Saltzburg, Austria, October 26-30, 1970.]footnote:3[R. Dams, J.A. Robbins, K. A. Rahn, and J. W. Winchester, "Nondestructive Neutron Activation Analysis of Air Pollution Particulates," Analytical Chemistry 42, pp. 861-867, 1970.]footnote:4[K.S. Pillay, C. C. Thomas, Jr., and C. M. Hyche, "Neutron Activation Analysis of Inorganic Constituents of Airborne Particulates," Nuclear Technology 10, pp. 224-231, 1971.]footnote:5[D. Gray, D. M. McKown, M. Kay, M. Eichor, and J. R. Vogt, "Determination of the Trace Element Levels in Atmospheric Pollutants by Instrumental Neutron Activation Analysis," IEEE Transactions on Nuclear Science, NS-19, No. 1, pp. 194-198, 1972.]footnote:6[L. A. Rancitelli, J. A. Cooper, and R. W. Perkins, "Multielement Characterization of Atmospheric Aerosols by Instrumental Neutron Activation Analysis," Comparative Studies of Food and Environmental Contamination, IAEA-SM-175/24, pp. 431-454, 1974.]footnote:7[T. M. Tanner, J. A. Young, and J. A. Cooper, "Multielement Analysis of St. Louis Aerosols by Nondestructive Techniques," Chemosphere 3, pp. 211-220, 1974.] have shown that the relative trace elements (especially those of anthropogenic origin) may vary widely from city to city. Air samples were collected by major aircraft, 20-30 miles downwind of 11 major cities from St. Louis eastward, in December 1974. We sought to determine whether the trace element concentration ratios differ sufficiently from city to city so the source of atmospheric contaminants at rural locations can be determined by comparing the concentration ratios measured at the rural locations and the concentration ratios characteristic of various urban-industrial complexes. This information would prove invaluable in the development and verification of computer models to predict the contaminant concentrations in the northeastern United States. Air samples were collected again downwind of three of these cities in June 1975 to determine whether the concentration ratios downwind of the cities.

== Experimental

One air filter sample was collected 20-30 miles downwind of each city over a 60-100 miles period while the Battelle-Northwest Cessna-411 twin engine aircraft flew a 20-30 mile track-perpendicular to the wind and 1000-2000 ft above the ground level. The air intake for the samples was a 10 cm diameter stainless steel pipe, extended at an angle forward through the side of the fuselage and 50 cm out into the air stream. Ram air pressure forced the air through a 27 cm diameter IPC filter paper at a rate of 23 m^3^/min, giving a linear velocity of 400 m/min across the filter. The air filters were returned to the Richland laboratory; the December samples have been analyzed for trace elements by x-ray fluorescence and instrumental neutron activation. The June samples are being analyzed now. During the collection of the air filters the SO2 and Aitken nuclei concentrations were monitored in real time using a Sinex SO~2~ monitor and a General Electric Aitken nucleus counter, respectively. 

In December 1974 samples were collected downwind of St. Louis, Indianapolis, Columbus, Pittsburgh, Bethlehem, Baltimore, Washington DC, and New York City, in that order. The choice of cities depended partly on the prevailing weather conditions. A few cities, such as Cleveland and Detroit, that we had intended to sample were issued because of bad weather. Samples were also collected in rural areas on flights between cities, and upwind of Washington DC-Baltimore-Philadelphia. In June 1975 samples were collected upwind and downwind of Indianapolis, Columbus, and Pittsburg.

== Results

The trace element concentrations measured for December 1974 are supported in *Tables 1 and 2*. The sulfur was in the form of sulfates. The average trace element concentrations measured at ground level, on an arc perpendicular to the wind 20 miles downwind of St. Louis, but Tanner, et al.footnote:7[] on July 17, 1973, and the concentrations measured in New York City by Rancitelli, et. al.footnote:6[] during March 1972 are also reported for comparison. The ratios of the concentrations of trace elements to concentrations of iron and lanthanum (two elements generally considered primarily crustal in origin) were compared to the ratios typical of crustal material. Thus we could determine which elements were present in amounts greater than could be accounted for by crustal material. The ratios indicate that most of the S, Cl, Zn, As, Se, Br, Mo, Sb, Hg, and Pb were of noncrustal origin, and therefore were presumably anthropogenic, although the chlorine could have been of marine origin. Vanadium, Na, and possibly Ca also appeared to be primarily of non-crustal origin for some of the cities. The ratios of the concentrations Mg, Al, Sc, Ti, Cr, Mn, Sr, Sm, Eu, Ta, and Co to the concentrations of Fe and La were similar to the ratios in crustal materials. Still, these elements could possibly have had significant anthropogenic contributions to their concentration since 1) the crustal concentrations are not very well known and are variable, and 2) there could be a significant anthropogenic contribution to the Fe and La concentrations downwind of cities.

The concentration ratios of selected pairs of uncorrelated elements of noncrustal origin are shown in *Table 3*. The ratios varied considerably, sometimes by more than two orders of magnitude between different cities. Generally, however, some of the ratios were significantly different between any two given cities. Each concentration ratio varied significantly between some pairs of cities, but not between others. For each pair of cities, the concentration ratios of elements of noncrustal origin which differed by more than an order of magnitude for the two cities are shown in *Table 4*. For most of the city pairs several elemental ratios differed by more than an order of magnitude. St. Louis-Allentown, Indianapolis-Rochester, and Indianapolis-Washington were the only city pairs which did not have at least one concentration ratio differing by more than an order of magnitude. The elemental concentration ratios may be used to distinguish between the plumes of different cities only if the ratios in the plumes remain relatively constant with time and distance downwind of the cities, at least until the plumes of different cities intersect. The concentration ratios measured by Tanner, et al.footnote:7[] at ground level from 20 - 80 miles downwind of St. Louis showed very little change with distance downwind of St. Louis.

The ratios must also be relatively independent or at least vary predictably with time, if they are to be used to distinguish between the plumes of different cities. The various concentration ratios of anthropogenic elements measured downwind of St. Louis in the summers of 1972 through 1975 as part of the Metromex program and in 1974 have averaged about 40% between different days. The various ratios measured in New York City on July 17, 1973, by Rancitelli, et. al.footnote:6[] and those measured downwind of New York on December 12, 1974, also averaged about 40%. However, the various ratios measured by aircraft downwind of Pittsburgh on December 13, 1975, and those measured on June 13, 1975, averaged only 22%. These concentration ratios measured at different times downwind of a given city differ by far less than the order of magnitude or more difference between ratios of different cities. Thus, the ratios are probably constant enough with time to be used to distinguish between the plumes of different cities.

Probably a large part of the variance between concentration ratios measured at ground level on different days resulted from the large scatter of the elemental concentrations measured in samples collected at ground level over 1-2-hr periods. For example, the lead concentrations between sequential samples collected at a given location downwind of St. Louis in the summer of 1974 varied by 35%. The concentrations measured in samples collected by aircraft have shown much less variation. The Pb concentrations measured at three different altitudes downwind of Pittsburgh on June 13, 1975, and concentrations measured at three different altitudes downwind of St. Louis in August of 1975 averaged variances of only 14%. The concentration ratios measured in samples collected while flying crosswind downwind of a city are probably much more representative of the city plume as a whole than are ratios measured at ground level.

The elemental concentration ratios in the plume of a city will be unique only if the elements in the plume were introduced into the atmosphere primarily by that city, and were not already present in the air beforehand. The concentrations of most anthropogenic elements were appreciably lower in the samples collected upwind of Columbus, Indianapolis, and Pittsburgh in June of 1975 than in the samples collected downwind of these cities. The concentrations of S, Zn, Se, Pb, As, and Br upwind of Pittsburgh averaged 40% of the concentrations downwind of Pittsburgh. When the upwind concentrations were subtracted from the downwind concentrations to obtain the net concentrations produced by Pittsburgh their ratios changed by an average of only 28%. However, rural samples collected farther east in December 1974 generally contained considerably higher concentrations of the anthropogenic trace elements. In fact, the concentrations measured in the sample collected on a flight from upwind (west) of Washington, DC to upwind (west) of Philadelphia contained higher concentrations of some of the elements than did the samples collected downwind of Philadelphia, Baltimore, or Washington, DC. Elemental concentrations will have to be measured both upwind and downwind of cities to obtain the net addition of elemental contaminants by the cities in cases where the air entering the cities is heavily contaminated. Possibly the elemental concentration ratios characteristic of the plumes of the eastern seaboard cities may be measured only when the wind is from the east.

== Summary and Conclusions

The plumes of eleven northeastern cities could be distinguished from one another from differences in the measured elemental concentrations ratios. The measurements of elemental concentration ratios downwind of St. Louis during project Metromex  indicate that the ratios remain relatively constant with distance downwind, at least until another major plume is intersected. The concentration ratios measured downwind of St. Louis, New York, Indianapolis, Columbus, and Pittsburgh on different dates were somewhat different, but the changes in the ratios with time were unlikely to be great enough to prevent the use of the ratios to distinguish between the plumes of different cities. To obtain accurate values for the ratios characteristic of a given city, the upwind concentrations should be subtracted from the downwind concentrations to obtain the net addition by the city.