[id="con_concentration_removal_st_louis_{con-concentration-removal-st-louis}"]
include::../attributes.adoc[]
:stem: latexmath

== Introduction

The St. Louis metropolitan area injects large quantities of pollutant materials into the atmosphere. These contaminants are carried large distances by the prevailing winds and may affect regions considerably downwind of St. Louis. The downwind decreases in the atmospheric concentrations of these contaminants with time and distance depending upon atmospheric mixing processes, wet and dry deposition on the earth’s surface, and in some cases, chemical conversion processes. The relative importance of mixing processes versus removal processes in decreasing the contaminant concentrations downwind of St. Louis may be determined by comparing the concentrations of nonconservative contaminants with those of conservative contaminants. Trichloroflouromethane, which is released into the atmosphere primarily by aerosol spray cans, is essentially conservative, having a residence time in the atmosphere of several years. CO may also be relatively conservative.

== Experimental

The concentrations of trace elements, sulfates, SO~2~, CO, and trichloroflouromethane are being measured in air samples collected upwind, in, and downwind of St. Louis on August 3-9, 1975 to determine the atmospheric concentrations of these contaminants produced by St. Louis, and to determine the rates at which the concentrations decrease downwind of St. Louis. Aerosol samples were collected for trace element analysis using HiVol pumps to draw air through _1_1 cm_ diameter Whatman-41 filter paper at a flow rate of about _0.6 m^3^ min^-1^_. Samples were collected for SO~2~ analysis by bubbling air through sodium tetrachloromercurate solutions at a rate of _1 ℓ / min_. Air samples for trichlorofluoromethane and CO analysis were obtained using a sampler which collects whole air by slowly drawing a piston up a cylinder. These samples were transferred to evacuated _460 cm^3^_ gas cylinders for storage.

On each sampling day one set of air samples was collected upwind of St. Louis. Sequential samples were collected on the roof of the 11-story Federal Building in downtown St. Louis within a mile or so of the St. Louis Gateway Arch. Six people equipped with mobile air sampling equipment collected air samples from _10 - 130 miles_ downwind of the St. Louis Arch. Each person collected one set of _1-hr_ air samples either _10_ or _20 miles_ downwind of the Arch, then moved several more miles downwind to collect a set of _2-hr_ air samples, and then moved downwind again to collect another _2-hr_ set of samples. The distance they moved downwind between samples was chosen so that their average rate of travel downwind was about the same as the rate at which the air traveled. In this manner, a grid of air sampling stations was set up which moved downwind with the air. Air sampling was begun at around 1100 each day and continued throughout the afternoon.

The Battelle Cessna-411 aircraft was used to collect air samples at three elevations in the mixed layer above the downwind air sampling stations on August 3, 4, 5, 7 and 8. Each sample was collected over a 45-min period while the Cessna was flying a racetrack pattern perpendicular to the wind. One vertical profile was taken on August 5, and profiles were taken at two distances downwind on the other days.

== Results

The analysis of the samples has not been completed, so results will be presented for only some of the sampling days in this report. On August 3 through 6 the wind was primarily from the north at about _8 - 10 mph_ and the contaminant concentrations for the 4 days were plotted together. Since the wind direction varied somewhat from day to day, the coordinate system for each day was rotated until the prevailing wind direction was equal to the average wind direction for the 4 days.

=== Trichlorofluoromethane

The concentrations of the conservative gas trichlorofluoromethane for August 3 through 6, 1975 are plotted in *Figure 1*. The concentrations decreased by a factor of around five between the Federal Building in downtown St. Louis and the samples collected 10 miles downwind of the Arch, as a result of vertical mixing through the mixed layer, and possibly horizontal mixing. Farther downwind the concentrations decreased more slowly. The concentrations _130 miles_ downwind averaged 65% of the concentrations _40 miles_ downwind. These results indicate that atmospheric mixing will decrease contaminant concentrations rapidly for the first _10_ or _20 miles_ downwind of the source, as the contaminant becomes mixed through the mixing layer, but that beyond that distance mixing will only slowly decrease concentration. In general, the chemically nonreactive anthropogenic contaminants measured downwind of St. Louis have shown a rapid decrease in concentration followed by much slower decrease.

=== Carbon Monoxide

The CO concentrations of August 3 through 6 are plotted in *Figure 2*. The measured CO concentrations downwind of St. Louis perhaps should not be taken too seriously due to possible contamination from CO emitted by the gasoline generators used to power the HiVol samplers. Even though care was taken to collect the samples for CO analysis upwind of the generators, several of the samples were obviously contaminated and had to be disregarded. The CO concentrations also showed a very rapid decrease between downtown and _10 miles_ downwind followed by a much slower decrease. The average concentration decreased 35% between 40 miles downwind and _130 miles_ downwind.

=== Lead

The Pb concentrations on August 4 are plotted in *Figure 3*. This is the only day on which the analysis for Pb is complete. Pb is introduced into the atmosphere primarily by automobile exhaust. The Pb concentrations measured by aircraft are also shown in the figure. The Pb concentrations decreased rapidly between the Federal Building and _10 miles_ downwind of the Arch, presumably as a result of atmospheric mixing. Beyond 10 miles the concentrations decreased more slowly. The Pb concentrations decreased by 60% between _40 miles_ downwind and _130 miles downwind_. The trichlorofluoromethane and CO analyses indicate that only about a 5% decrease can be accounted for by dilution due to atmospheric mixing, leaving a 40% decrease due to dry deposition. Pb measurements carried out in 1973 indicate that 70% of the Pb is present on particles smaller than _0.3 μ_ in diameter and only 10% is present on particles larger than _3 μ_, so settling cannot be a major cause of the Pb concentration decreases. Therefore, most of the Pb concentration decrease between 30 and 120 miles downwind must have been due to dry deposition resulting from diffusion. Assuming that the Pb concentration was constant through a _4000-ft_ mixed layer, and that the wind speed was 8 mph, then a deposition velocity of _1.2 cm sec^-1^_ would be required to decrease the Pb concentration by 40% in 90 miles. The Pb concentrations measured by aircraft tended to be somewhat higher than the ground level concentrations, indicating that deposition at the earth’s surface lowered the surface level concentrations more than the higher elevation concentrations. Therefore the above calculated deposition velocity is probably greater than the true deposition velocity.

=== Zinc

The Zn concentrations measured at ground level and by aircraft on August 4 are plotted in *Figure 4*. The Zn in the atmosphere is primarily anthropogenic. The Zn concentration in one of the samples collected 12 miles downwind of St. Louis was nearly three times the concentration measured in downtown St. Louis, suggesting a source of Zn either downwind of the downtown sampling site or east of the site. The downtown Zn concentrations were not significantly greater than the average of two other concentrations measured _11 miles_ downwind of the Arch, indicating that there were no major Zn sources within a few miles upwind of the downtown sampling site. The Zn concentration decreased by a factor of three from _40 - 120 miles_ downwind of the Arch, a rate of decrease about equal to that of Pb. For some reason the Zn concentrations measured by aircraft were considerably higher than those measured at ground level.

=== Sulfure Dioxide

The SO2 concentrations for August 3-6 are plotted in *Figure 5*. The SO2 concentrations decreased an average of _79 ppb_ at the Federal Building to about _20 ppb 10 miles_ downwind of the Arch and then increases again to about 50 ppb 30 miles downwind of the Arch. Probably the low SO~2~ concentrations _10 miles_ downwind of the Arch resulted from the fact that SO~2~ released from stacks passed over these sampling locations and only reached ground level farther downwind. The sampling location on top of the Federal Building may have sampled SO~2~ that had not yet reached ground level. The SO~2~ concentrations measured in samples collected by aircraft _50 miles_ downwind of the Arch on August 5 were _10_, _78_, and _89 ppb_ at _1500_, _3000_, and _5000 ft_ above sea level, respectively; significantly higher than the ground level concentrations. Beyond _50 miles_ the SO~2~ concentrations at ground level decreased rapidly, to a value of _6 ppb 120 miles_ downwind of the Arch. This is a much faster decrease than shown by Pb and presumably results from the reaction of SO~2~ with vegetation and the earth’s surface. The sulfate measurements indicate that only about 10% of SO~2~ concentration decrease could be accounted for by the conversion of SO2 to sulfates in the atmosphere.

=== Sulfates

The sulfate concentrations on August 3 and 4 are plotted in *Figure 6* in units of _μg S / m^3^_ air. The samples for the other sampling days have not been analyzed for sulfates as yet. The sulfate concentration, like the SO~2~ concentration, increased to a maximum _40 miles_ downwind of the Arch and then decreased. However, the sulfate concentration at the Arch was about the same as that _10 miles_ other compounds such as Pb, for comparison purposes. A low-volume flow system is provided for deposition tubes for collection of SO~2~. These systems represent some modification of a preliminary system developed for the Environmental Protection Agency. That system was tested in a 1975 experimental program downwind of the Centralia, Washington, fossil fuel plant. The present systems have been designed to minimize the possibility of sample contamination or modification due to the sampling method. All collectors are mounted on the meteorological tower. Additional systems were developed to more precisely measure total volume flow. Carefully measured flow, temperature and pressure with less than 1% error in combination with positive displacement flow meters allows flow volumes between levels to be assessed with a relative error estimated to be 1% or less. The meteorological data are recorded at high frequency on industrial-standard magnetic tape. The line pressures are manually recorded using manometers. Every effort has been made to improve the measurement accuracy.

Aerosol samples obtained will be analyzed by a specifically-developed x-ray fluorescence procedures designed to minimize the relative error between samples; insuring as accurate gradients as are possible.

The deposition tubes will be used for SO~2~ samples. Analysis of the meteorological profile structure will allow the determination of deposition velocities. We believe that the measurement precision is sufficient to provide the necessary accuracy to determine significant deposition rates for the pollutant species under consideration. Development of an SO~2~ fluxmeter is being considered to serve as a totally independent and absolutely direct method of measuring deposition.

The application of the profile method of determining deposition rates for other pollutant species was found in the earlier study to require other specialized techniques. In particular the determination of the gradients of highly reactive gases (such as O~3~ and NO) was found to be best performed using a vertically roving intake line with real time analysis. An effort has been initiated to develop this capability further.

Verification of results from the set of pilot experiments will allow the planning of experiments to assess the dry removal rates of the S effluents from use western fossil fuels. Specification of the removal rates will permit assessment of the air quality terrestrial impacts associated with the development and utilization of these resources.

NOTE: The report mentions a *Figure 6*, but it was not included in the report.
