[id="con_regional_air_quality_nw_energy_{con-regional-air-quality-nw-energy}"]
include::../attributes.adoc[]
:stem: latexmath

== Introduction

The {AS} Department is engaged in a regional air quality assessment of the Pacific Northwest in conjunction with {Dprog}. Our objective is to estimate the air quality in the {PNW} and provide information needed to assess the effects on terrestrial environments caused by deposition and washout of airborne pollutants, from development of the region's energy resources. A thorough assessment of these impacts requires detailed knowledge of the strength and geographic distribution of present and future energy-related emissions throughout the region (including emissions from energy facilities themselves, as well as secondary emissions resulting from the community and transportation growth that will inevitably occur as resources are developed) and knowledge of the atmospheric transport and diffusion properties throughout the region.

== Emissions

The energy-related pollutant emissions will be obtained as part of the output of the energy/economic sectors of a regional model being developed in the {RSP}. Emission factors will be obtained from the literaturefootnote:1[1. University of Oklahoma, the Science and Public Policy Program, "Energy Alternatives: A Comparative Analysis," available from the U.S. Government Printing Office, Washington D.C., 1975.], footnote:2[Environmental Protection Agency, "Compilation of Air Pollutant Emission Factors," publication No. AP-42, available from Environmental Protection Agency, Research Triangle Park, NC, April, 1975.] will be incorporated into this model to convert the amount of fuel burned or converted in various categories (such as electrical or coal conversion, transportation and space heating) and the amount of particulates released by process industries and agricultural activities, into total emissions of sulfur and nitrogen oxides, particulates, trace elements, carbon monoxide, and hydrocarbons. The emission inventory can be divided into two basic categories: 1) primary or point source emissions from large fuel burning or conversion facilities such as power plants and gasification plants, and 2) secondary or area source emissions from space heating, transportation, and related industries.

== Transport and Diffusion Model

A regional scale transport and diffusion model which accounts for the spatial and temporal variations in the wind fieldfootnote:3[L. L. Wendell and D. C. Powell, "Regional Transport, Dispersion and Removal of Atmospheric Pollutants," Pacific Northwest Laboratories Annual Report for 1974 to the U.S. Atomic Energy Commission  Division of Biomedical and Environmental Research, Part 3, Atmospheric Sciences, BNWL-1950, PT 3, Battelle, Pacific Northwest Laboratories, Richland, Washington, February 1975.], footnote:4[4. L. L. Wendell, D. C. Powell and R. L. Drake, "A Regional Scale Model for Computing Deposition and Ground Level Air Concentration of SO2 and SO4 from an Elevated Source," Pacific Northwest Laboratories Annual Report for 1975 to the USERDA Division of Biomedical and Environmental Research, Part 3, Atmospheric Sciences, BNWL-2000, PT 3, Battelle-Northwest, Richland, Washington, 1976.] is being used to estimate ground level air quality impacts of present and future energy develpment activities. This model interpolates the mean winds between stem:[100 \, m] and stem:[1000 \, m] above the ground, measured every 12 hr at approximately 34 sites in or adjacent to the area of the {PNW} covered in the {RSP} (*Figure 1*). Trajectories of pollutant transport are then determined from these wind fields. Standard difussion relations are used to estimate plume dispersion. Removal processes such as dry deposition, precipitation scavenging, and chemical transformations are incorporated into the model.

For incorporation into the {PNW} {RAMo}, calculations will be made from a long term set of meteorological data to develop annual average air quality concentrations, on a grid of receptor points normalized to the composite emissions occuring throughout the region. This matrix of normalized concentrations can then be coupled to the other sectors of the {RAMo} to calculate air quality and deposition processes for exogenously specified scenarios. The rate and cumulative amount of surface-deposited pollutants will be made available to the bioproductivity sector for computation of effects over time.

== Program Status

A preliminary investigation of transport has been made for the six large or proposed coal-fired power plants listed in *Table 1*. *Figure 2* shows the plume trajectories for these plants for a 4-day period in April 1974 computed from the trajectory model. The existing wind data are influenced, to some extent, by large topographic features such as the Rocky Mountains. Analytical methods are being considered to incorporate the effect of the topographic features such as the {CasMt}, {ColBas}, and {WilVal}.

Preliminary computations of ground-level concentration, deposition, and scavenging of sulfur dioxides and sulfates from large coal-fired plants in the Northwest have also been made. Precipitation scavenging is computed using mean monthly precipitation data extrapolated to a fine-mesh grid. Eventually, estimates of annual average ground level concentrations and surface deposition of sulfur dioxides and sulfates will be made on a grid with roughly 2000 "receptor points" spaced approximately stem:[38 \, km] apart.