[id="ref_changelog_{ref-changelog}"]
include::../attributes.adoc[]

== Changelog

=== 2026

==== 11 January 2026 - 17 January 2026, BNWL-2000, pp. 69-83

* Created "Resuspension in a Generalized Area Source"

* Created "Approximations and Solutions for the Deposition-Resuspension Problem"

* Created "Some Comments on the Surface Boundary Conditions for the Diffusion-Deposition-Resuspension Problem"

* Created "Rate-Limiting Aspects of the Dry Deposition of Gases"

* Created "Some Comments on the Surface Boundary Conditions for the Diffusion-Deposition-Resuspension Problem"

* Reference Material

- Created "Attributes" and added all of the author names; relevant publication, organization and location names, retroactively applied and added attributes.adoc to all modules

- Separately created image attributes in the above file, same deal

- Updated "Compounds & Isotopes", "Glossary of Terms", and 1 meta-reference diagram created, and 3 of the meta-reference diagrams added to assembly

* Miscellaneous

- So much fixing leveloffset title errors

==== 04 January 2026 - 10 January 2026, BNWL-2000, pp. 65-68

* Created "Modeling Preliminaries for Dry Deposition to a Canopy"

* Reference Material

- Updated "Glossary of Terms"

=== 2025

==== 14 December 2025 - 20 December, 2025, BNWL-2000, pp. 61-63

* Created "Deposition and Resuspension" section assembly, pp. 64-126

* Created "Further Studies on a Low Level Model to Compute Montgomery Stream Functions"

* Reference Material

- Updated "Glossary of Terms", "Greek Letters & Definitions"

NOTE: "Further Studies on a Low Level Model to Compute Montgomery Stream Functions" signals the end of the second section of the report.

==== 7 December 2025 - 13 December, 2025, BNWL-2000, pp. 53-60

* Created "Field Measurement of the Effect of Filter Orientation on Sampling of a Particulate Tracer"

* Reference Material

- Added the Diagrams to a new module with the placeholder name "Basic Diagrams", placeholder text included with it, as well as "Resources for Reports"

- Updated "Glossary of Terms", "Important Names & Locations to Hanford"

* Formatting Changes

- Found additional modules in need of IDs and corrected that, general bugs

* *HaPpY BiRtHdAy to me! I am longer in my _prime_.* (Get it? 37 is a prime number!)

==== 30 November 2025 - 6 December 2025, BNWL-2000, pp. 39-52

* Created "Variation of Plume Centerline Concentration with Time"

* Created "Some Observations of the Relative Contribution of Real Plume Diffusion and of Meander to Apparent Plume Diffusion"

* Created "Diffusion with Deposition at Short Range"

* Created "A Pitfall in the Application of Tensor Analysis to Fluid Mechanics"

* Created "Some Observations of the Relative Contribution of Real Plume Diffusion and Meander to Apparent Plume Diffusion"

* Reference Material

- Created "Greek Letters & Definitions"

- Updated "Glossary of Terms", "Elements & Their Atomic Numbers", "Compounds & Isotopes"

* Formatting Changes

- Utilized the LaTeX stem macro for Asciidoctor, added module IDs finally

- Unpublished reference module cataloging the glossary and elements references

NOTE: Pages ("pp.") refer to the page numbers in the original, printed document, *not* the PDF copy's page numbers.

==== 23 November 2025 - 29 November 2025, BNWL-2000, pp. 25-36

* Created "Baseline Air Quality Data from Colstrip, Montana"

* Created "A Simple Development of Covariant Differentiation"

* Created "Solvent Refined Coal - Organic Constituents Present in the Process"

* "Baseline Air Quality Data from Colstrip, Montana"

* Reference Material

- Created "Periodic Table of Elements"

- Updated "Glossary of Terms", "Elements & Their Atomic Numbers", "Compounds"

* Images

 - Created "Anion vs. Cation", "Periodic Table of Elements", "Radioactive Decay", "Gas Chromatography", "Acid - Base Scale"

==== 16 November 2025 - 22 November 2025, BNWL-2000, pp. iii, 2-25

* Created new entries for additional reports under the "Pacific Northwest Laboratory Annual Report for 1975 to the USERDA Division of Biomedical and Environmental Research Part 3 Atmospheric Sciences"

- "The Concentrations ^241^Pu and ^99^Tc in Surface Air at Richland, Washington"

- "Atmospheric Fallout During 1975 at Richland, Washington and Point Barrow, Alaska"

- "Lead (Pb) Concentrations Associated with 1000 mb Geostrophic Back Trajectories at Quillayute"

* Created "Transuranium Elements in the Atmosphere"

* Reference material

- Created new models explaining concepts in the glossary: radioactive decay, anions vs. cations, layers of the atmosphere

- Updated "Glossary of Terms", "Elements & Their Atomic Numbers", "Compounds", "Important Names & Locations"

NOTE: Any changes in the "Elements & Their Atomic Number" reference modules apply to both version unless otherwise noted. There is absolutely no reason to list them separately.

NOTE: Named entries are assumed to include all assemblies, concepts, and reference material.