[id="ref_changelog_{ref-changelog}"]
include::../attributes.adoc[]

== Changelog

=== 2026

==== 26 April 2026 - 2 May 2026, BNWL-2000, pp. 202-211

* Added "Simultaneous Aerosol Size Distributions and Turbidity Measurements over a Metropolitan Area"

* Added "Turbidity Variations over the Alton, {IL}, Airport During August 1975"

* Added "Aerosols and SO~2~ Measurements during the Da Vinci Balloon Flight"

* Added "Integration of Models for Atmospheric Processes" assembly

* Updated Glossary of Terms, attributes

==== 5 April 2026 - 11 April 2026, BNWL-2000, pp. 189-202

* Added "Aerosol Balance Equations: Theoretical Studies" (pp. 189-190)

* Added "Aerosol Balance Equations: Numerical Modeling" (pp. 191-195)

* Added "The Growth of Aerosol in an Urban Plume" (pp. 196-202)

* Updated Glossary of Terms, attributes

==== 15 March 2026 - 21 March 2026, BNWL-2000, pp. 179-188

* Created "Development of a No-Deposition Precipitation Sampler" (187-188)

* Created "A Design for Regional Precipitation Chemistry Measurement and Analysis" (185-186)

* Created "The Entrainment of Tracers Near the Sides of Convective Clouds" (179-184)

* Created Pollutant Transformations and Interactions assembly

* Updated Conceptual Diagrams assembly

* Updated Pollutant Scavenging assembly

* Updated Glossary of Terms, Important Names & Locations to Hanford, attributes

==== 1 March 2026 - 7 March 2026, BNWL-2000, pp. 166-178

* Created "Scavenging fo Urban Pollutants by Thunderstorm Rainfall: Numerical Experimentation"

* Created "A Computer Algorithm for Reduction and Presentation of Information from the BNW DC-3 Data Acquisition System"

* Created "Development of a DC-3 Aircraft for Atmospheric Pollution Research"

* Updated Glossary of Terms, attributes

==== 22 February 2026 - 28 February 2026, BNWL-2000, pp. 145-165

* Created "An Estimate of In-Cloud Scavenging of a Tracer Injected into Two Frontal Storms"

* Created "A Review of Moist Mesoscale Models with Possible Applicability to Precipitation Scavenging"

* Created "Design for In-Cloud Scavenging Experiments on the Olympic Peninsula"

* Created "Precipitation Scavenging Field Experiments in March 1975 on the Olympic Peninsula"

* Created "Rain Scavenging of Active Aerosol Particles from a Plume"

* Created "The Battelle-Northwest in-Cloud Scavenging Program - An Overview"

* Updated Glossary of Terms, Important Places & Locations, attributes

==== 15 February 2026 - 21 February 2026, BNWL-2000, pp. 133-136, 139-144

* Created "Synoptic Scale Wet and Dry Deposition"

* Created "Washout Ratios for Particulate Pollution with an Application to Convective Storms"

* Created "Approximations for the Precipitation Scavenging Rates for Polydisperse, Active, Aerosolized Pollutants"

* Updated Glossary of Terms, attributes

==== 1 February 2026 - 7 February 2026, BNWL-2000, pp. 112-126

* Created "A General Scavenging Formalism for the Precipitation Scavenging for Aerosol Particles"

* Created "Precipitation Scavenging of Monodisperse Aerosol Particles"

* Created "Comments on Diffusive Deposition at Smaller Fourier Numbers"

* Created assembly for "Pollutant Scavenging"

* Created "Concentrations and Rates of Removal of Contaminants from the Atmosphere In and Downwind of St. Louis"

* Created "Rususpension of Radioactive Isotopes Induced by Burning Forest Logging Slash"

* Created "Frequency of Dust Devils in the Hanford Reservation"

* Created "Wind Profiles in Dust Storms"

* Reference Material

- Updated Basic Diagrams assembly to contain radioactive decay

- Updated "Glossary of Terms", "Important Names & Locations", "About This Project"

* *Happy belated birthday Dad, who worked as a millwright at Hanford until 1992. He would have turned 70, but he https://www.legacy.com/us/obituaries/tricityherald/name/kyle-simpson-obituary?id=18318892[died] on February 3, 2013 at 57 years old (+3 days). I miss you.* For this reason, I added a photo to "About This Project".

==== 25 January 2026 - 31 January 2026, BNWL-2000, pp. 96-111

* Created "Frequency of Airborne Dust in the Continental United States"

* Created "Initial Observations of Airborne Concentrations of Small Particle Size Ranges During Two Dust Storms"

* Created "The Influence of Soil Insertion on Atmospheric Particle Size Distributions"

* Created "Particle Resuspension from Truck Traffic in a Cheat Grass Area"

* Reference Material

- Updated "Glossary of Terms" to include the equation to Cowling's approximation, "Conceptual Diagrams"

==== 18 January 2026 - 24 January 2026, BNWL-2000, pp. 89-95

* Created "An Experiment to Measure Particle Resuspension from a Large Annular Area"

* Created "Resuspension Rates from a Circular Field Source"

* Created "Field Deposition Velocity Measurements to a Sagebrush Canopy"

* Reference Matterial

- Created attributes for LaTeX equations

- Updated "Glossary of Terms", "Important Names & Locations to Hanford"

==== 11 January 2026 - 17 January 2026, BNWL-2000, pp. 69-89

* Created "Particle Deposition and Penetration through Vegetation Canopies and Tunnel Experiments"

* Created "Comparison of Deposition Velocities Predicted from Dimensionless Analysis Correlations"

* Created "Resuspension in a Generalized Area Source"

* Created "Approximations and Solutions for the Deposition-Resuspension Problem"

* Created "Some Comments on the Surface Boundary Conditions for the Diffusion-Deposition-Resuspension Problem"

* Created "Rate-Limiting Aspects of the Dry Deposition of Gases"

* Created "Some Comments on the Surface Boundary Conditions for the Diffusion-Deposition-Resuspension Problem"

* Reference Material

- Created "Attributes" and added all of the author names; relevant publication, organization and location names, retroactively applied and added attributes.adoc to all modules

- Separately created image attributes in the above file, same deal

- Updated "Compounds & Isotopes", "Glossary of Terms", and 1 meta-reference diagram created, and 3 of the meta-reference diagrams added to assembly

- Reworked the "Greek Alphabet" reference into a table

* Miscellaneous

- So many assembly "leveloffset" title errors

==== 04 January 2026 - 10 January 2026, BNWL-2000, pp. 65-68

* Created "Modeling Preliminaries for Dry Deposition to a Canopy"

* Reference Material

- Updated "Glossary of Terms", "Important Names & Locations"

=== 2025

==== 14 December 2025 - 20 December, 2025, BNWL-2000, pp. 61-63

* Created "Deposition and Resuspension" section assembly, pp. 64-126

* Created "Further Studies on a Low Level Model to Compute Montgomery Stream Functions"

* Reference Material

- Updated "Glossary of Terms", "Greek Letters & Definitions"

NOTE: "Further Studies on a Low Level Model to Compute Montgomery Stream Functions" signals the end of the second section of the report.

==== 7 December 2025 - 13 December, 2025, BNWL-2000, pp. 53-60

* Created "Field Measurement of the Effect of Filter Orientation on Sampling of a Particulate Tracer"

* Reference Material

- Added the Diagrams to a new module with the placeholder name "Basic Diagrams", placeholder text included with it, as well as "Resources for Reports"

- Updated "Glossary of Terms", "Important Names & Locations to Hanford"

* Formatting Changes

- Found additional modules in need of IDs and corrected that, general bugs

* *HaPpY BiRtHdAy to me! I am longer in my _prime_.* (Get it? 37 is a prime number!)

==== 30 November 2025 - 6 December 2025, BNWL-2000, pp. 39-52

* Created "Variation of Plume Centerline Concentration with Time"

* Created "Some Observations of the Relative Contribution of Real Plume Diffusion and of Meander to Apparent Plume Diffusion"

* Created "Diffusion with Deposition at Short Range"

* Created "A Pitfall in the Application of Tensor Analysis to Fluid Mechanics"

* Created "Some Observations of the Relative Contribution of Real Plume Diffusion and Meander to Apparent Plume Diffusion"

* Reference Material

- Created "Greek Letters & Definitions"

- Updated "Glossary of Terms", "Elements & Their Atomic Numbers", "Compounds & Isotopes"

* Formatting Changes

- Utilized the LaTeX stem macro for Asciidoctor, added module IDs finally

- Unpublished reference module cataloging the glossary and elements references

NOTE: Pages ("pp.") refer to the page numbers in the original, printed document, *not* the PDF copy's page numbers.

==== 23 November 2025 - 29 November 2025, BNWL-2000, pp. 25-36

* Created "Baseline Air Quality Data from Colstrip, Montana"

* Created "A Simple Development of Covariant Differentiation"

* Created "Solvent Refined Coal - Organic Constituents Present in the Process"

* "Baseline Air Quality Data from Colstrip, Montana"

* Reference Material

- Created "Periodic Table of Elements"

- Updated "Glossary of Terms", "Elements & Their Atomic Numbers", "Compounds"

* Images

 - Created "Anion vs. Cation", "Periodic Table of Elements", "Radioactive Decay", "Gas Chromatography", "Acid - Base Scale"

==== 16 November 2025 - 22 November 2025, BNWL-2000, pp. iii, 2-25

* Created new entries for additional reports under the "Pacific Northwest Laboratory Annual Report for 1975 to the USERDA Division of Biomedical and Environmental Research Part 3 Atmospheric Sciences"

- "The Concentrations ^241^Pu and ^99^Tc in Surface Air at Richland, Washington"

- "Atmospheric Fallout During 1975 at Richland, Washington and Point Barrow, Alaska"

- "Lead (Pb) Concentrations Associated with 1000 mb Geostrophic Back Trajectories at Quillayute"

* Created "Transuranium Elements in the Atmosphere"

* Reference material

- Created new models explaining concepts in the glossary: radioactive decay, anions vs. cations, layers of the atmosphere

- Updated "Glossary of Terms", "Elements & Their Atomic Numbers", "Compounds", "Important Names & Locations"

NOTE: Any changes in the "Elements & Their Atomic Number" reference modules apply to both version unless otherwise noted. There is absolutely no reason to list them separately.

NOTE: Named entries are assumed to include all assemblies, concepts, and reference material.