[id="ref_about_this_project_{ref-about-this-project}"]
include::../attributes.adoc[]

== About this project

This repository exists for a few reasons:

. My grandfather, {CLS}, was a meteorologist for the {HNR} and the {PNL} during {WW2} and the {CW} in {rich}, {WA}. He was born in 1927 and given to a (Depression-era) orphanage. I don't know when he moved to {WA}. He was 60 years old when I was born, and he died in the early 2000s when I was in the seventh grade. I miss him. I read the work to be close to him again.

. Dad, Kyle Simpson, was also a journeyman millwright at Hanford until 1992.

. In the "current era" of the {US} on the road to fascism and the potential withdrawal from NATO, Hanford's history with nuclear weapons testing isn't just part of our history; it's part of our present.

. I am a technical writer in "cutting edge" technology in software development including cybersecurity, automation, and {os}. Partially, I feel connected to a man who also worked in cutting edge technology in the nuclear era and wrote technical reports about it. However banal though, I want to keep current on written documentation.

[#img-dad-wedding]
[caption="Mom & Dad's Wedding 1985", alt="{dad-wedding-alt}"]
image::{dad-wedding-img}[Mom & Dad's Wedding 1985]

The photo above is my grandparents and father at my parents' wedding in 1985. From left to right are Grandma, Dad, and Grandpa.

== Why should YOU give a shit?

If the {US}s pulls out of NATO, we resume nuclear war tensions with conflicting nations, and so many more of them than before have nukes of their own. This history is our history but hopefully not our future. The cultural impact of {WW2} and the nuclear arms race is significant enough that my generation - despite not being raised with the drills of my cousins' and father's generations - shouldn't forget it. It's still within living memory.

Also Research Gate tried to charge me $300 per article when the PDF copies displayed they should be freely distributed. They're morally bankrupt, and I'm petty. So here we are, I guess.

== I don't recognize any of those names or places

Hanford was critical to the success of the United States in {WW2} and a part of The {MP}, the project through which nuclear arms research was conducted during the war. The research continued after the end of that war through the {CW}. That research included the infamous Green Run experiment. While fascinating in a "wow, that's messed up" kind of way, that's not within the scope of my project. The same is true for the pollution of the Columbia River and everyone downwind's extra cancer risk (including mine).

== Let's get "The Simpson's" jokes out of the way

My name is {me-a}, and I was born in Pasco, {WA} in 1987. Because it's been the source of jokes _my entire life anyway_, that does mean:

. I was born in the Pacific Northwest like Matt Groening. He is from Oregon, but the same river Hanford used to cool its reactors - the Columbia River - linked both states.

. I was born the year "The Simpson's" aired on "The Tracy Ulman Show". The show premiered in May, making it seven months older than me. The full series premiered in 1989. Because of our name, I was allowed to watch it as a kid, which was unthinkable in the 1990's. Bart is not a horrible little boy who's like a little Satan in disguise, but you wouldn't know that by the way he was discussed _then_. Stewie Griffin doesn't get dragged the way Bart ever did.

. If you remember older epsisodes like "Bart the Daredevil" (S02E08) and "El Viaje Misterioso de Nuestro Jomer" (S08E09), as well as newer episodes like "On a Clear Day, I Can't See My Sister" (S16E12), "Mona Leaves-a" (S19E19), and "Fland Canyon" (S27E19), there's clear recognition of a side desert somewhere in the near proximity of Springfield, which is roughly equivalent to Eastern Washington's climate.

. I was raised in the 1990's, the culture of the men in Dad's generation included crummy tasting (imo) beer, and I am approximately as much older to my little brother as Lisa is to Maggie.

. My father and grandfather worked at Hanford - a nuclear plant - which had massive safety concerns and violations that are ongoing including being the "most toxic place in the Western *hemisphere*" due to the pollution of the Columbia River. That would sorta put it on the same level as Springfield per "The Simpson's Movie", ironically the last movie we saw as a family unit of the four of us.

If you make a joke about it to me, there's a good chance I'll find it funny.

== Challenges

=== AsciiDoc Conversion

There are several things I didn't know how to do prior to this project that I either had to write down for myself as a reference or eventually "clicked" after using it so many times.

* Information architecture: So far (Feb. 4, 2026), there is one large paper and three smaller papers. The larger paper contains 313 pages (in PDF form) of individual reports gathered together for the {PNL} in 1975. It was easier to organize everything by paper when there were just a few and treating them as top level modules made sense. That changed when I had to convert a report with multiple sections with multiple papers each.

* LaTeX: The last time I took a math class was in 2007, and so I never had to use LaTeX or any "real" technology to understand what I was doing - outside of the required TI-83 calculator which I could (at best) write a program that did the quadratic formula for me. Nuclear physics equations were another ballgame. Eventually, all of the "coding" equations clicked for me and I began hand-writing it without any trouble. That was basically overnight.

* Attributes, attributes, attributes: If you've gone through a lot of these reports, author names, organizations, and journals reappear over and over. Moreover, they weren't consistently referenced. Using attributes was the only way to do any of that without losing my head.

* Tables: I knew how to do tables. I had no idea how using two headers would "mess with" the table organization. I had to decide between tables that had the second header missing one line, showing every line in the grid, or very long header names to compensate. That was extremely frustrating.

* Math precision: You may have noticed the reports aren't written with consistency with regard to how many decimal places out they use, or whether or not they're written as logarithms or as standard numbers. I chose to remain consistent to what was written, but for scanning that data, my next step is going to write more consistent, scannable tables. However, the way it displays now is true to how it was published.