= Changelog

.30 November 2025 - 6 December 2025, BNWL-2000, pp. 39-47

* Created "A Pitfall in the Application of Tensor Analysis to Fluid Mechanics"

* Created "Diffusion with Deposition at Short Range"

* Created "Some Observations of the Relative Contribution of Real Plume Diffusion and Meander to Apparent Plume Diffusion"

* Reference Material

- Created "Greek Letters & Definitions"

- Updated "Glossary of Terms", "Elements & Their Atomic Numbers", "Compounds"

* Formatting Changes

- Utilized the LaTeX stem macro for Asciidoc

.23 November 2025 - 29 November 2025, BNWL-2000, pp. 25-36

* Created "Baseline Air Quality Data from Colstrip, Montana"

* Created "A Simple Development of Covariant Differentiation"

* Created "Solvent Refined Coal - Organic Constituents Present in the Process"

* "Baseline Air Quality Data from Colstrip, Montana"

* Reference Material

- Created "Periodic Table of Elements"

- Updated "Glossary of Terms", "Elements & Their Atomic Numbers", "Compounds"

* Images

 - Created "Anion vs. Cation", "Periodic Table of Elements", "Radioactive Decay", "Gas Chromatography", "Acid - Base Scale"

.16 November 2025 - 22 November 2025, BNWL-2000, pp. iii, 2-25

* Created new entries for additional reports under the "Pacific Northwest Laboratory Annual Report for 1975 to the USERDA Division of Biomedical and Environmental Research Part 3 Atmospheric Sciences"

- "The Concentrations ^241^Pu and ^99^Tc in Surface Air at Richland, Washington"

- "Atmospheric Fallout During 1975 at Richland, Washington and Point Barrow, Alaska"

- "Lead (Pb) Concentrations Associated with 1000 mb Geostrophic Back Trajectories at Quillayute"

* Created "Transuranium Elements in the Atmosphere"

* Reference material

- Created new models explaining concepts in the glossary: radioactive decay, anions vs. cations, layers of the atmosphere

- Updated "Glossary of Terms", "Elements & Their Atomic Numbers", "Compounds", "Important Names & Locations"

NOTE: Any changes in the "Elements & Their Atomic Number" reference modules apply to both version unless otherwise noted. There is absolutely no reason to list them separately.

NOTE: Named entries are assumed to include all assemblies, concepts, and reference material.