== Changelog

.17-18 November 2025 - BNWL-2000 pp. iii, 2-11, 11-

* Assemblies

- Added "Pacific Northwest Laboratory Annual Report for 1975 to the Userda Division of Biomedical and Environmental Research Part 3 Atmospheric Sciences" which serves as an upper-layer assembly for the reports therein:

- Added "Ozone, Radionuclide and Particulate Correlations in Air at Quillayute, Washington"

- Added "Lead (Pb) Concentrations Associated with 1000 mb Geostrophic Back Trajectories at Quillayute" (incomplete)

- Updated "Measurement of Particulate Plume Depletion by Comparison with Inert Gas Plumes" and "Transuranium Elements in the Atmosphere" to contain their labeled reference number

* Modules

- *Concept Module:* "Ozone, Radionuclide and Particulate Correlations in Air at Quillayute, Washington"

- *Concept Module:* "Lead (Pb) Concentrations Associated with 1000 mb Geostrophic Back Trajectories at Quillayute"

* References

- *Reference module:* "Ozone, Radionuclide and Particulate Correlations in Air at Quillayute, Washington" references

- *Reference module:* "Ozone, Radionuclide and Particulate Correlations in Air at Quillayute, Washington" table 1

- *Reference module:* "Ozone, Radionuclide and Particulate Correlations in Air at Quillayute, Washington" figures 1-9

- *Reference module:* "Lead (Pb) Concentrations Associated with 1000 mb Geostrophic Back Trajectories at Quillayute" references

- *Reference module:* "Lead (Pb) Concentrations Associated with 1000 mb Geostrophic Back Trajectories at Quillayute" tavle 1 & placeholder for table 2

- *Reference module:* "Measurement of Particulate Plume Depletion by Comparison with Inert Gas Plumes" figures 1-4 _alt text_

- *Reference Module:* Changelog

- *Elements & Their Atomic Number:* Beryllium, Be, 4; Ce, Cerium, 58; Florine, FP, 9; Niobium, Nb, 41; O, Oxygen, 8; Pb, Lead, 82 (still unlinked)

- *Glossary:* anthropogenic, cosmogenic, decay per minute (DPM), diurnal, first order kinetics, geostrophic, inversion layer, KSCM compounds (KCSM), Lagrangian, Liquid Metal Breeder Reactor (LMBR), oceanographic (still unlinked)

- *Names & Locations:* Liquid-Metal Fast-Breeder Reactor (LMFBR), National Ambient Air Quality Standard (NAAQS), Quillayute Air Reference Station

NOTE: Any changes in the "Elements & Their Atomic Number" reference modules apply to both version unless otherwise noted. There is absolutely no reason to list them separately.

NOTE: Considering adding a separate figure that outlines the different layers of the earth from the ground up.

* Images

- "Ozone, Radionuclide and Particulate Correlations in Air at Quillayute, Washington" figures 1-9

- "Lead (Pb) Concentrations Associated with 1000 mb Geostrophic Back Trajectories at Quillayute" figures 1-2 (unlinked)

- Basic atmosphere diagram

.Inception

* Created repository, file structure

* Assemblies

- "Scientific reports from Hanford & the Pacific Northwest Laboratories in the Cold War" which serves as the top layer assembly for all reports and papers

- "Measurement of Particulate Plume Depletion by Comparison with Inert Gas Plumes"

- "Prediction of Environmental Exposures from Sources near the Ground on the Hanford Experimental Data"

- "Transuranium Elements in the Atmosphere"

* Images

- "Measurement of Particulate Plume Depletion by Comparison with Inert Gas Plumes" figures 1-8

- "Prediction of Environmental Exposures from Sources near the Ground on the Hanford Experimental Data" figures 1-7

- "Transuranium Elements in the Atmosphere" figures 1-3

* Modules

- *Concept module:* "Measurement of Particulate Plume Depletion by Comparison with Inert Gas Plumes"

- *Concept module:* "Prediction of Environmental Exposures from Sources near the Ground on the Hanford Experimental Data"

- *Concept module:* "Transuranium Elements in the Atmosphere"

- *Reference module:* About this project (unlinked)

- *Reference module:* Compound Names & Shorthand (unlinked)

- *Reference module:* Elements & Their Atomic Number, Sorted by Atomic Number (unlinked)

- *Reference module:* Elements & Their Atomic Number, Sorted by Element (unlinked)

- *Reference module:* Glossary of Terms (unlinked)

- *Reference module:* Important Names & Locations to Hanford (unlinked)

- *Reference module:* "Measurement of Particulate Plume Depletion by Comparison with Inert Gas Plumes" Figures

- *Reference module:* "Measurement of Particulate Plume Depletion by Comparison with Inert Gas Plumes" References

- *Reference modules:* "Measurement of Particulate Plume Depletion by Comparison with Inert Gas Plumes" Tables 1-3

- *Reference module:* "Prediction of Environmental Exposures from Sources near the Ground on the Hanford Experimental Data" Figures

- *Reference module:* "Prediction of Environmental Exposures from Sources near the Ground on the Hanford Experimental Data" References

- *Reference modules:* "Prediction of Environmental Exposures from Sources near the Ground on the Hanford Experimental Data" Tables 1-3

- *Reference module:* "Transuranium Elements in the Atmosphere" Figures

- *Reference module:* "Transuranium Elements in the Atmosphere" Tables 1-8

* PDFs

- "Measurement of Particulate Plume Depletion by Comparison with Inert Gas Plumes" source text

- "Prediction of Environmental Exposures from Sources near the Ground on the Hanford Experimental Data" source text

- "Transuranium Elements in the Atmosphere" source text

NOTE: Images are uploaded as .png, modules and assemblies are uploaded as .adoc, and PDFs are uploaded as .pdf. (Sorry, I know you know.)

NOTE: "Prediction of Environmental Exposures from Sources near the Ground on the Hanford Experimental Data" figures 8-11 remain to be added.