[id="ref_rate_limiting_aspects_of_the_dry_deposition_figures_{ref-rate-limiting-dry-deposition-figures}"]
include::../attributes.adoc[]

== Figure 1: A Plot of Equation (5) Which Demonstrates that the Dry Deposition Velocity for Gases is Frequently Dictated by Other than Atmospheric Phenomena (Neg 754519-9)

[#img-rate-limiting-gases-1]
[caption="A Plot of Equation (5) Which Demonstrates that the Dry Deposition Velocity for Gases is Frequently Dictated by Other than Atmospheric Phenomena", alt={rate-limiting-grases-alt-1}]
image::{rate-limiting-gases-img-1}[A Plot of Equation (5) Which Demonstrates that the Dry Deposition Velocity for Gases is Frequently Dictated by Other than Atmospheric Phenomena]

== Figure 2: A Second Plot of Equation (5) (Neg-754519-10)

[#img-rate-limiting-gases-2]
[caption="A Second Plot of Equation (5)", alt={rate-limiting-gases-alt-2}]
image::{rate-limiting-gases-img-2}[A Second Plot of Equation (5)]

For a given diffusivity in the sink D and atmospheric diffusivity _K_, then _β^-½^_ is a constant multiplied by the overall partition coefficient _H~o~_, which in turn is proportional to the Henry’s law constant. Consequently, by conveniently shifting the upper abscissa and normalizing the deposition velocities, as measured by Hill and Chamberlainfootnote:4[A. C. Hill and E. M. Chamberlain, “The Removal of Water Soluble Gases from the Atmosphere by Vegetation,” Atmosphere-Surface Exchange of Particulate and Gaseous Pollutants, R. J. Engelmann and G. A. Schmel, Coords., ERDA Symposium Series, to be published, 1976.] by their measured value for _HF_, it can be seen that the theory is capable of reflecting the measured data for the dry deposition of gases to the alfalfa. The error bars on the data are subjectively estimated by the author.