[id="assembly_concentrates_and_removal_report_1975_44_63_{cassembly-concentrates_and_removal-MAIN}"]

= Air and Dispersion

Surveys are being made of effluents released into the atmosphere, within the source areas, to distances covering several states, and on hemispheric scales. Through these efforts, the Atmospheric Sciences and Radiological Sciences Departments are identifying the most urgent air pollution problems and continually reassessing them to set priorities for more detailed investigations.

Fallout measurements and evaluations are continuing with the essential identification and study of worldwide nuclear test debris, nuclear power effluents appearing in the atmosphere, and the transfer of these worldwide distributions to the surface. New Survey efforts are measuring the ambient distributions of pollutants from fossil fuel facilities. Measurements are being made describing the wide variety of pollutants introduced into the atmosphere from individual coal facility sources; measurements of pollutant characteristics from urban complexes are defining their physical and chemical characteristics as they are transported large distances. Reference levels of pollutants in air entering a given region are also being defined. The emphasis in ongoing reference measurements on the coast of Washington State will assure future comprehensive coverage of nonnuclear pollutants in addition to the continuing nuclear contaminant evaluations.

* Survey of ambient airborne pollutants

* Radioactive fallout rates and mechanisms

* Coal conversion atmospheric chemistry

include::../assemblies/assembly_simple_development_of_covariant_differentiation.adoc[leveloffset=+1]
include::../assemblies/assembly_a_pitfall_in_the_application_of_tensor_analysis_to_fluid_mechanics.adoc[leveloffset=+1]
include::../assemblies/assembly_diffusion_with_deposition_at_short_range.adoc[leveloffset=+1]
include::../assemblies/assembly_some_observations_of_the_relative_contribution_of_real_plume.adoc[leveloffset=+1]
include::../assemblies/assembly_variation_of_plume_centerline_concentration_with_time.adoc[leveloffset=+1]
include::../assemblies/assembly_field_measurement_of_the_effect_of_filter_orientation.adoc[leveloffset=+1]
include::../assemblies/assembly_variation_of_sample_wind_components_spectra.adoc[leveloffset=+1]
include::../assemblies/assembly_further_studies_on_a_low_level_model_montgomery.adoc[leveloffset=+1]